[[ConfluenceContent]]
[[BeanInjection-BeanInjection]]
Bean Injection
^^^^^^^^^^^^^^

We support the injection of various resources using @EndpointInject or
@BeanInject. This can be used to inject

* link:endpoint.html[Endpoint] instances which can be used for testing
when used with link:mock.html[Mock] endpoints; see the
link:spring-testing.html[Spring Testing] for an example.
* link:producertemplate.html[ProducerTemplate] instances for
link:pojo-producing.html[POJO Producing]
* client side proxies for link:pojo-producing.html[POJO Producing] which
is a simple approach to link:spring-remoting.html[Spring Remoting]

[[BeanInjection-Using@BeanInject]]
Using @BeanInject
+++++++++++++++++

From *Camel 2.13* onwards you can inject beans (obtained from the
link:registry.html[Registry]) into your beans such as `RouteBuilder`
classes.

For example to inject a bean named foo, you can enlist the bean in the
link:registry.html[Registry] such as in a Spring XML file:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<bean id="foo" class="com.foo.MyFooBean"/>
----

And then in a Java `RouteBuilder` class, you can inject the bean using
`@BeanInject` as shown below:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
public class MyRouteBuilder extends RouteBuilder {

   @BeanInject("foo")
   MyFooBean foo;

   public void configure() throws Exception {
     ..
   }
}
----

If you omit the name, then Camel does a lookup by type, and injects the
bean if there is exactly only one bean of that type enlisted in the
link:registry.html[Registry].

[source,brush:,java;,gutter:,false;,theme:,Default]
----
   @BeanInject
   MyFooBean foo;
----
