[[ConfluenceContent]]
[[CamelMavenPlugin-CamelMavenPlugin]]
Camel Maven Plugin
~~~~~~~~~~~~~~~~~~

The
https://svn.apache.org/repos/asf/camel/trunk/tooling/maven/camel-maven-plugin[Camel
Maven Plugin] allows you to run your
link:enterprise-integration-patterns.html[Enterprise Integration
Patterns] using link:spring.html[Spring] for
link:dependency-injection.html[Dependency Injection] inside Maven along
with being able to support link:visualisation.html[Visualisation] along
with integration of the link:visualisation.html[Visualisation] diagrams
into the standard maven reports for your project.

[[CamelMavenPlugin-GoalsSupported]]
Goals Supported
^^^^^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Documentation |Goal |Description
|link:camel-run-maven-goal.html[camel:run] |camel:run |Boots up Camel in
the context of a separately initiated Java thread using the
link:spring.html[Spring] configuration at *META-INF/spring/*.xml* and
runs your routing rules. From Camel 2.10 onwards also OSGi blueprint is
supported to load from *OSGI-INF/blueprint/*.xml* (requires to configure
the plugin to use blueprint).

|link:camel-embedded-maven-goal.html[camel:embedded] |camel:embedded
|Boots up Camel using the link:spring.html[Spring] configuration at
*META-INF/spring/*.xml* and runs your routing rules. From Camel 2.10
onwards also OSGi blueprint is supported to load from
*OSGI-INF/blueprint/*.xml* (requires to configure the plugin to use
blueprint).

|link:camel-dot-maven-goal.html[camel:dot] |camel:dot |*deprecated*:
Generates DOT files and then HTML, PNG, SVG files for your EIP routing
rules with integration into Maven Reports. This plugin *only* supports
Spring XML files.

|https://github.com/apache/camel/blob/master/tooling/maven/camel-maven-plugin/src/main/docs/camel-maven-plugin.adoc[camel:validate]
|camel:validate |*Camel 2.19:* To validate your source code for invalid
Camel endpoint uris.
|=======================================================================

[[CamelMavenPlugin-Addingtheplugintoyourpom.xml]]
Adding the plugin to your pom.xml
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Add the following in your <build><plugins> section

[Note]
====


You may override the default Spring application context file uri
*META-INF/spring/*.xml* by using the applicationContextUri property in
the camel-maven-plugin configuration. Paths may be split using a
semi-colon (;).

====

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<plugin>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-maven-plugin</artifactId>
  <configuration>
    <applicationContextUri>META-INF/spring/*.xml;YOUR_FILE_NAME_IN_THE_CLASS_PATH.xml</applicationContextUri>
  </configuration>
</plugin>
----

You can also specify what Main class to use when running the plugin. By
default this is `org.apache.camel.spring.Main`.

 

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<plugin>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-maven-plugin</artifactId>
  <!-- optional, default value: org.apache.camel.spring.Main -->
  <configuration>
    <mainClass>mypackage.boot.camel.CamelStartup</mainClass>
  </configuration>
</plugin>
----

[[CamelMavenPlugin-Filebasedspringconfigurationfiles]]
File based spring configuration files
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

From Camel 1.4 onwards loading Spring context files via a file location
is also supported. You configure this with the
*fileApplicationContextUri* option. Paths may be split using a
semi-colon (;). This sort of file location is useful for web application
projects that store spring configuration files in WEB-INF. It can also
be used to replace configuration that requires an OSGi container with an
equivalent non-OSGi configuration.

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<plugin>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-maven-plugin</artifactId>
  <configuration>
    <fileApplicationContextUri>
      src/main/webapp/WEB-INF/camel*.xml;
      src/test/spring/test-context.xml
    </fileApplicationContextUri>
  </configuration>
</plugin>
----

[[CamelMavenPlugin-Classpath]]
Classpath
^^^^^^^^^

The plugin will construct a classpath of any Maven dependency with scope
"compile". The classpath is output as an INFO log statement upon
startup.

[[CamelMavenPlugin-RouteInformation]]
Route Information
^^^^^^^^^^^^^^^^^

Information about the generated routes is available through the GraphViz
report, and also through the log statements generated by the run goal.
If you would like to see this information then add a log4j (or other
commons-logging implementation) config file with the following levels.

*src/main/resources/log4.properties*

[source,brush:,java;,gutter:,false;,theme:,Default]
----
log4j.rootLogger=INFO, stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n

log4j.logger.org.apache.camel.impl.DefaultCamelContext=DEBUG, stdout
log4j.additivity.org.apache.camel.impl.DefaultCamelContext=false
----

This should produce a log statement similar to:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
670  [org.apache.camel.spring.Main.main()] DEBUG org.apache.camel.impl.DefaultCamelContext  
  - Adding routes from: Routes: [Route[ [From[jms:queue:queueA]] -> [To[jms:queue:queueB], To[jms:queue:queueC]]]] routes: []
----

[[CamelMavenPlugin-IntegrationintoMavenReports]]
Integration into Maven Reports
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

If you add the camel-maven-plugin to your <reporting> section of your
pom you will automatically get the
link:visualisation.html[Visualisation] reporting generated for your
project as part of the regular maven site generation.

For example add the following into your pom

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<project>
  ...
  <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.camel</groupId>
        <artifactId>camel-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </reporting>  
</project>
----

Then when you run

[source,brush:,bash;,gutter:,false;,theme:,Default]
----
mvn site
----

Your context will be booted up via the *META-INF/spring/*.xml* files,
the DOT file generated and a nice HTML report created.

[Info]
====
 **GraphViz DOT required**

Note to get the nice HTML, PNG and SVG outputs from the DOT files you
will need to install the http://graphviz.org[GraphViz] DOT executable
and add it to your PATH so that the plugin can invoke DOT to generate
the PNG/SVG files.

For more details see the link:camel-dot-maven-goal.html[camel:dot].

====
