[[ConfluenceContent]]
[[ControlBusComponent-ControlBusComponent]]
ControlBus Component
~~~~~~~~~~~~~~~~~~~~

*Available as of Camel 2.11*

The *`controlbus:`* component provides easy management of Camel
applications based on the link:controlbus.html[Control Bus] EIP pattern.
For example, by sending a message to an link:endpoint.html[Endpoint] you
can control the lifecycle of routes, or gather performance statistics.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
controlbus:command[?options]
----

Where *`command`* can be any string to identify which type of command to
use.

[[ControlBusComponent-Commands]]
Commands
^^^^^^^^

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Command |Description
|`route` |To control routes using the *`routeId`* and *`action`*
parameter.

|`language` a|
Allows you to specify a link:language.html[Language] to use for
evaluating the message body.

The result, if any, is returned in the message body.

|=======================================================================

[[ControlBusComponent-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|`routeId` |`null` |To specify a route by its *`id`*. The special
keyword *`current`* indicates the current route.

|`action` |`null` a|
Can be one of:

* `start`
* `stop`
* `suspend`
* `resume`
* `status`
* `stats`

To either start or stop a route, or to get the status of the route as
output in the message body.

From *Camel 2.11.1*: use *`suspend`* and *`resume`* to either suspend or
resume a route or *`stats`* to get performance statistics, in XML
format, for the route whose id is given by the *`routeId`* option. If
*`routeId`* is not defined, then statistics for the entire
link:camelcontext.html[CamelContext] will be returned.

|`async` |`false` a|
Whether to execute the control bus task asynchronously.

[Warning]
====


*Important:* If this option is enabled, then any result from the task is
*not* set on the link:exchange.html[Exchange]. This is only possible if
executing tasks synchronously.

====

|`loggingLevel` |`INFO` |Logging level used for logging when task is
done, or if any exceptions occurred during processing the task.
|=======================================================================

You can append query options to the URI in the following format,
*`?option=value&option=value&...`*

[[ControlBusComponent-Examples]]
Examples
^^^^^^^^

[[ControlBusComponent-UsingtherouteCommand]]
Using the `route` Command
+++++++++++++++++++++++++

The route command allows you to do common tasks on a given route very
easily, for example to start a route, you can send an empty message to
this endpoint:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
template.sendBody("controlbus:route?routeId=foo&action=start", null);
----

To get the status of the route, you can do:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
String status = template.requestBody("controlbus:route?routeId=foo&action=status", null, String.class);
----

[[ControlBusComponent-Gettingperformancestatistics]]
Getting performance statistics

*Available as of Camel 2.11.1*

This requires JMX to be enabled (is by default) then you can get the
performance statics per route, or for the
link:camelcontext.html[CamelContext]. For example to get the statics for
a route named *`foo`*, we can do:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
String xml = template.requestBody("controlbus:route?routeId=foo&action=stats", null, String.class);
----

The returned statics is in XML format. Its the same data you can get
from JMX with the *`dumpRouteStatsAsXml`* operation on the
*`ManagedRouteMBean`*.

To get statics for the entire link:camelcontext.html[CamelContext] you
just omit the *`routeId`* parameter as shown below:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
String xml = template.requestBody("controlbus:route?action=stats", null, String.class);
----

[[ControlBusComponent-Usinglanguage]]
Using link:simple.html[Simple] language
+++++++++++++++++++++++++++++++++++++++

You can use the link:simple.html[Simple] language with the control bus,
for example to stop a specific route, you can send a message to the
*`controlbus:language:simple`* endpoint containing the following
message:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
template.sendBody("controlbus:language:simple", "${camelContext.stopRoute('myRoute')}");
----

As this is a void operation, no result is returned. However, if you want
the route status you can do:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
String status = template.requestBody("controlbus:language:simple", "${camelContext.getRouteStatus('myRoute')}", String.class);
----

*Notice:* its easier to use the *`route`* command to control lifecycle
of routes. The `language` command allows you to execute a language
script that has stronger powers such as link:groovy.html[Groovy] or to
some extend the link:simple.html[Simple] language.

For example to shutdown Camel itself you can do:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
template.sendBody("controlbus:language:simple?async=true", "${camelContext.stop()}");
----

Notice we use *`async=true`* to stop Camel asynchronously as otherwise
we would be trying to stop Camel while it was in-flight processing the
message we sent to the control bus component.

[Tip]
====


You can also use other languages such as link:groovy.html[Groovy], etc.

====

[[ControlBusComponent-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:controlbus.html[ControlBus] EIP
* link:jmx.html[JMX] Component
* Using link:camel-jmx.html[JMX] with Camel
