[[ConfluenceContent]]
[[DataFormat-DataFormat]]
Data Format
~~~~~~~~~~~

Camel supports a pluggable DataFormat to allow messages to be marshalled
to and from binary or text formats to support a kind of
link:message-translator.html[Message Translator].

The following data formats are currently supported:

* Standard JVM object marshalling
** link:serialization.html[Serialization]
** link:string.html[String]

* Object marshalling
** link:avro.html[Avro]
** link:boon.html[Boon]
** link:hessian.html[Hessian]
** link:json.html[JSON]
** link:protobuf.html[Protobuf]
** link:yaml-data-format.html[YAML]

* Object/XML marshalling
** link:castor.html[Castor]
** link:jaxb.html[JAXB]
** link:xmlbeans.html[XmlBeans]
** link:xstream.html[XStream]
** link:jibx.html[JiBX]
** link:jackson-xml.html[Jackson XML]

* Object/XML/Webservice marshalling
** link:soap.html[SOAP]

* Direct JSON / XML marshalling
** link:xmljson.html[XmlJson]

* Flat data structure marshalling
** link:beanio.html[BeanIO]
** link:bindy.html[Bindy]
** link:csv.html[CSV]
** link:edi.html[EDI]
** link:flatpack-dataformat.html[Flatpack DataFormat]
** link:univocity-parsers-formats.html[uniVocity-parsers formats]

* Domain specific marshalling
** link:hl7-dataformat.html[HL7 DataFormat]

* Compression
** link:gzip-data-format.html[GZip data format]
** link:zip-dataformat.html[Zip DataFormat]
** link:zip-file-dataformat.html[Zip File DataFormat]
** link:lzf-data-format.html[LZF Data Format]
** link:tar-dataformat.html[Tar DataFormat]

* Security
** link:crypto.html[Crypto]
** link:crypto.html[PGP]
** link:xmlsecurity-dataformat.html[XMLSecurity DataFormat]

* Misc.
** link:base64.html[Base64]
** link:custom-dataformat.html[Custom DataFormat] - to use your own
custom implementation
** link:mime-multipart.html[MIME-Multipart]
** link:rss.html[RSS]
** link:tidymarkup.html[TidyMarkup]
** link:syslog.html[Syslog]
** link:ical.html[ICal]
** link:barcode-data-format.html[Barcode]- to read and generate barcodes
(QR-Code, PDF417, ...)

And related is the following:

* link:dataformat-component.html[DataFormat Component] for working with
link:data-format.html[Data Format]s as if it was a regular
link:component.html[Component] supporting link:endpoint.html[Endpoint]s
and link:uris.html[URIs].
* link:dozer-type-conversion.html[Dozer Type Conversion] using Dozer for
type converting POJOs

[[DataFormat-Unmarshalling]]
Unmarshalling
^^^^^^^^^^^^^

If you receive a message from one of the Camel
link:components.html[Components] such as link:file2.html[File],
link:http.html[HTTP] or link:jms.html[JMS] you often want to unmarshal
the payload into some bean so that you can process it using some
link:bean-integration.html[Bean Integration] or perform
link:predicate.html[Predicate] evaluation and so forth. To do this use
the *unmarshal* word in the link:dsl.html[DSL] in Java or the
link:xml-configuration.html[Xml Configuration].

For example

[source,brush:,java;,gutter:,false;,theme:,Default]
----
DataFormat jaxb = new JaxbDataFormat("com.acme.model");

from("activemq:My.Queue").
  unmarshal(jaxb).
  to("mqseries:Another.Queue");
----

The above uses a named DataFormat of _jaxb_ which is configured with a
number of Java package names. You can if you prefer use a named
reference to a data format which can then be defined in your
link:registry.html[Registry] such as via your link:spring.html[Spring]
XML file.

You can also use the DSL itself to define the data format as you use it.
For example the following uses Java serialization to unmarshal a binary
file then send it as an ObjectMessage to link:activemq.html[ActiveMQ]

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("file://foo/bar").
  unmarshal().serialization().
  to("activemq:Some.Queue");
----

[[DataFormat-Marshalling]]
Marshalling
^^^^^^^^^^^

Marshalling is the opposite of unmarshalling, where a bean is marshalled
into some binary or textual format for transmission over some transport
via a Camel link:component.html[Component]. Marshalling is used in the
same way as unmarshalling above; in the link:dsl.html[DSL] you can use a
DataFormat instance, you can configure the DataFormat dynamically using
the DSL or you can refer to a named instance of the format in the
link:registry.html[Registry].

The following example unmarshals via serialization then marshals using a
named JAXB data format to perform a kind of
link:message-translator.html[Message Translator]

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("file://foo/bar").
  unmarshal().serialization(). 
  marshal("jaxb").
  to("activemq:Some.Queue");
----

[[DataFormat-UsingSpringXML]]
Using Spring XML
^^^^^^^^^^^^^^^^

This example shows how to configure the data type just once and reuse it
on multiple routes

You can also define reusable data formats as Spring beans

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<bean id="myJaxb" class="org.apache.camel.model.dataformat.JaxbDataFormat">
  <property name="prettyPrint" value="true"/>
  <property name="contextPath" value="org.apache.camel.example"/>
</bean>  
----
