[[ConfluenceContent]]
[[Direct-DirectComponent]]
Direct Component
~~~~~~~~~~~~~~~~

The *`direct:`* component provides direct, synchronous invocation of any
consumers when a producer sends a message exchange. This endpoint can be
used to connect existing routes in the *same* camel context.

[Tip]
====
 **Asynchronous**

The link:seda.html[SEDA] component provides asynchronous invocation of
any consumers when a producer sends a message exchange.

====

[Tip]
====
 **Connection to other camel contexts**

The link:vm.html[VM] component provides connections between Camel
contexts as long they run in the same *JVM*.

====

[[Direct-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,text;,gutter:,false;,theme:,Default]
----
direct:someName[?options]
----

Where *`someName`* can be any string that uniquely identifies the
endpoint.

[[Direct-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|`allowMultipleConsumers` |`true` a|
*@deprecated *

If set to *`false`*, then when a second consumer is started on the
endpoint, an *`IllegalStateException`* is thrown.

*Will be removed in Camel 2.1:* Direct endpoint does not support
multiple consumers.

|`block` |`false` |*Camel 2.11.1:* If sending a message to a direct
endpoint which has no active consumer, the producer will block
for *`timeout`* milliseconds waiting for a consumer to become active.

|`timeout` |`30000` |*Camel 2.11.1:* The timeout value, in milliseconds,
to block, when enabled, for an active consumer.

|`failIfNoConsumers` |`true` |*Camel 2.16.0*: Indicates whether the
producer should fail by throwing an exception when sending to
a *`direct`* endpoint with no active consumers.
|=======================================================================

You can append query options to the URI in the following
format: *`?option=value&option=value&...`*

 

[[Direct-Samples]]
Samples
^^^^^^^

In the route below we use the direct component to link the two routes
together:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("activemq:queue:order.in")
    .to("bean:orderServer?method=validate")
    .to("direct:processOrder?block=true&timeout=5000");

from("direct:processOrder")
    .to("bean:orderService?method=process")
    .to("activemq:queue:order.out");
----

And the sample using spring DSL:

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
   <route>
     <from uri="activemq:queue:order.in"/>
     <to uri="bean:orderService?method=validate"/>
     <to uri="direct:processOrder?failIfNoConsumers=false"/>
  </route>

  <route>
     <from uri="direct:processOrder"/>
     <to uri="bean:orderService?method=process"/>
     <to uri="activemq:queue:order.out"/>
  </route>    
----

See also samples from the link:seda.html[SEDA] component, how they can
be used together.

[[Direct-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:seda.html[SEDA]
* link:vm.html[VM]
