[[ConfluenceContent]]
[[ETLExample-ExtractTransformLoad(ETL)Example]]
Extract Transform Load (ETL) Example
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The link:etl.html[ETL] (Extract, Transform, Load) example shows how to
load data into a database using Camel. In this example we will poll for
files, transform them and then store them in the database via the
link:jpa.html[JPA] component.

[[ETLExample-Overview]]
Overview
^^^^^^^^

This example lives in the _examples/camel-example-etl_ directory and
will poll for XML files in the child _src/data_ directory. When the
files are detected, they are converted, using the fallback
link:jaxb.html[JAXB] link:type-converter.html[Type Converter] to a
PersonDocument class. This POJO is then transformed using a custom
link:type-converter.html[Type Converter] into a CustomerEntity bean
using the CustomerTransformer class. Then this bean is stored in the
database via the link:jpa.html[JPA] component.

The code for this example is as follows

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Java Class |Purpose
|https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/java/org/apache/camel/example/etl/CustomerEntity.java[CustomerEntity]
|The JPA entity bean (i.e. a POJO with @Entity)

|https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/java/org/apache/camel/example/etl/PersonDocument.java[PersonDocument]
|The JAXB2 POJO used to parse the XML

|https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/java/org/apache/camel/example/etl/CustomerTransformer.java[CustomerTransformer]
|The custom link:type-converter.html[Type Converter] used to convert a
PersonDocument into a CustomerEntity

|https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/java/org/apache/camel/example/etl/EtlRoutes.java[EtlRoutes]
|The Camel routing link:dsl.html[DSL] to define the flow from the files
to the converter to the link:jpa.html[JPA] endpoint
|=======================================================================

Then there is the spring configuration file in
https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/resources/META-INF/spring/camel-context.xml[src/resources/META-INF/services/camel-context.xml]
which defines the JPA template and tells Camel to look in the
*org.apache.camel.example.etl* package to find its routes.

[[ETLExample-Codewalkthrough]]
Code walkthrough
^^^^^^^^^^^^^^^^

So lets start with the route definition in
https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/java/org/apache/camel/example/etl/EtlRoutes.java[EtlRoutes]

[source,brush:,java;,gutter:,false;,theme:,Default]
----
public class EtlRoutes extends SpringRouteBuilder {
    public void configure() throws Exception {

        from("file:src/data?noop=true")
            .convertBodyTo(PersonDocument.class)
            .to("jpa:org.apache.camel.example.etl.CustomerEntity");

        // the following will dump the database to files
        from("jpa:org.apache.camel.example.etl.CustomerEntity?consumeDelete=false&delay=3000&consumeLockEntity=false")
            .setHeader(Exchange.FILE_NAME, el("${in.body.userName}.xml"))
            .to("file:target/customers");
    }
}
----

The above sets up a route from the _src/data_ directory. Notice we're
using the _noop_ mode of the link:file2.html[File] component so that the
files are not moved or deleted when they are processed (so when the tool
is restarted they will be processed again). Because the file consumer
uses a memory based
http://camel.apache.org/idempotent-consumer.html[Idempotent Consumer]
every file is only processed once (per program run) (see also _noop_ and
_idempotent*_ options from http://camel.apache.org/file2.html[file]
component).

We're converting the body of the message to a
https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/java/org/apache/camel/example/etl/PersonDocument.java[PersonDocument]
which since this POJO as an @XmlRootElement annotation from
link:jaxb.html[JAXB] will kick in the link:type-converter.html[Type
Converter] to use JAXB to unmarshall the object.

Then we send the message with a PersonDocument body to the
link:jpa.html[JPA] endpoint. Notice how this endpoint specifies the
expected type. So the link:type-converter.html[Type Converter] is gonna
try convert the PersonDocument to a
https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/java/org/apache/camel/example/etl/CustomerEntity.java[CustomerEntity].
Here Camel will find the
https://github.com/apache/camel/blob/master/examples/camel-example-etl/src/main/java/org/apache/camel/example/etl/CustomerTransformer.java[CustomerTransformer]
class which has an @Converter method

[source,brush:,java;,gutter:,false;,theme:,Default]
----
@Converter
public final class CustomerTransformer {

    private static final Logger LOG = LoggerFactory.getLogger(CustomerTransformer.class);

    private CustomerTransformer() {
    }

    /**
     * A transformation method to convert a person document into a customer
     * entity
     */
    @Converter
    public static CustomerEntity toCustomer(PersonDocument doc, Exchange exchange) throws Exception {
        EntityManager entityManager = exchange.getIn().getHeader(JpaConstants.ENTITYMANAGER, EntityManager.class);
        TransactionTemplate transactionTemplate = exchange.getContext().getRegistry().lookupByNameAndType("transactionTemplate", TransactionTemplate.class);

        String user = doc.getUser();
        CustomerEntity customer = findCustomerByName(transactionTemplate, entityManager, user);

        // let's convert information from the document into the entity bean
        customer.setUserName(user);
        customer.setFirstName(doc.getFirstName());
        customer.setSurname(doc.getLastName());
        customer.setCity(doc.getCity());

        LOG.info("Created object customer: {}", customer);
        return customer;
    }

    /**
     * Finds a customer for the given username
     */
    private static CustomerEntity findCustomerByName(TransactionTemplate transactionTemplate, final EntityManager entityManager, final String userName) throws Exception {
        return transactionTemplate.execute(new TransactionCallback<CustomerEntity>() {
            public CustomerEntity doInTransaction(TransactionStatus status) {
                entityManager.joinTransaction();
                List<CustomerEntity> list = entityManager.createNamedQuery("findCustomerByUsername", CustomerEntity.class).setParameter("userName", userName).getResultList();
                CustomerEntity answer;
                if (list.isEmpty()) {
                    answer = new CustomerEntity();
                    answer.setUserName(userName);
                    LOG.info("Created a new CustomerEntity {} as no matching persisted entity found.", answer);
                } else {
                    answer = list.get(0);
                    LOG.info("Found a matching CustomerEntity {} having the userName {}.", answer, userName);
                }

                return answer;
            }
        });
    }

}
----

which performs the necessary conversion to an entity bean which is then
stored in the database

[[ETLExample-Runningtheexample]]
Running the example
^^^^^^^^^^^^^^^^^^^

To run the example we use the link:camel-maven-plugin.html[Camel Maven
Plugin]. For example from the source or binary distribution the
following should work

[source,brush:,java;,gutter:,false;,theme:,Default]
----
cd examples/camel-example-etl
mvn camel:run
----

If you prefer you can just run the Main directly using

[source,brush:,java;,gutter:,false;,theme:,Default]
----
mvn compile exec:java
----

Please note that when you run the example for the first time, the
converter `CustomerTransformer` will not be able to find any entities
inside the database, so that along the logs written into the console you
should see:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
...
thread #0 - file://src/data] CustomerTransformer            INFO  Created a new CustomerEntity Customer[userName: james firstName: null surname: null] as no matching persisted entity found.
...
thread #0 - file://src/data] CustomerTransformer            INFO  Created a new CustomerEntity Customer[userName: hiram firstName: null surname: null] as no matching persisted entity found.
...
----

However running the example for a second time, as the entites have been
already inserted into the database, the log should now say:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
...
thread #0 - file://src/data] CustomerTransformer            INFO  Found a matching CustomerEntity Customer[userName: james firstName: James surname: Strachan] having the userName james.
...
thread #0 - file://src/data] CustomerTransformer            INFO  Found a matching CustomerEntity Customer[userName: hiram firstName: Hiram surname: Chirino] having the userName hiram.
...
----

Failing that you can run the Main from inside your IDE if you prefer.
Follow the link:building.html[Building] instructions to create an
Eclipse/IDEA project to import
