[[ConfluenceContent]]
[[FineGrainedControlOveraChannel-Introduction]]
Introduction
~~~~~~~~~~~~

When sending an link:exchange.html[Exchange] to an
link:endpoint.html[Endpoint] you can either use a
link:routes.html[Route] or a
link:producertemplate.html[ProducerTemplate]. This works fine in many
scenarios. However you may need to guarantee that an exchange is
delivered to the same endpoint that you delivered a previous exchange
on. For example in the case of delivering a batch of exchanges to a
link:mina.html[MINA] socket you may need to ensure that they are all
delivered through the same socket connection. Furthermore once the batch
of exchanges have been delivered the protocol requirements may be such
that you are responsible for closing the socket.

[[FineGrainedControlOveraChannel-UsingaProducer]]
Using a Producer
~~~~~~~~~~~~~~~~

To achieve fine grained control over sending exchanges you will need to
program directly to a Producer. Your code will look similar to:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  CamelContext camelContext = ...

  // Obtain an endpoint and create the producer we will be using.
  Endpoint endpoint = camelContext.getEndpoint("someuri:etc");
  Producer producer = endpoint.createProducer();
  producer.start();

  try {
    // For each message to send...
    Object requestMessage = ...
    Exchange exchangeToSend = producer.createExchange();
    exchangeToSend().setBody(requestMessage);
    producer.process(exchangeToSend);
    ...

  } finally {
    // Tidy the producer up.
    producer.stop();
  }
----

In the case of using Apache MINA the producer.stop() invocation will
cause the socket to be closed.
