[[ConfluenceContent]]
[[Ganglia-Gangliacomponent]]
Ganglia component
~~~~~~~~~~~~~~~~~

[[Ganglia-AvailableasofCamel2.15.0]]
Available as of Camel 2.15.0
++++++++++++++++++++++++++++

Provides a mechanism to send a value (the message body) as a metric to
the http://ganglia.info[Ganglia] monitoring system.  Uses the gmetric4j
library.  Can be used in conjunction with standard
http://ganglia.info[Ganglia] and
https://github.com/ganglia/jmxetric[JMXetric] for monitoring metrics
from the OS, JVM and business processes through a single platform.

You should have a Ganglia gmond agent running on the machine where your
JVM runs.  The gmond sends a heartbeat to the Ganglia infrastructure,
camel-ganglia can't send the heartbeat itself currently.

On most Linux systems (Debian, Ubuntu, Fedora and RHEL/CentOS with EPEL)
you can just install the Ganglia agent package and it runs automatically
using multicast configuration.  You can configure it to use regular UDP
unicast if you prefer.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

 

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-ganglia</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

[[Ganglia-URIformat]]
URI format
~~~~~~~~~~

[source,brush:,java;,gutter:,false;,theme:,Default]
----
ganglia:address:port[?options]
----

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[Ganglia-GangliacomponentandendpointURIoptions]]
Ganglia component and endpoint URI options
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[cols=",,,",options="header",]
|=======================================================================
|Name |Default value |Description |Override with header
|mode |MULTICAST |Send the UDP metric packets using MULTICAST or UNICAST
| 

|ttl |5 |If using multicast, set the TTL of the packets | 

|wireFormat31x |true |Use the wire format of Ganglia 3.1.0 and later
versions.  Set this to false to use Ganglia 3.0.x or earlier. | 

|groupName |Java |The group that the metric belongs to. | 

|prefix |  |(optional) Prefix the metric name with this string and an
underscore. | 

|metricName |metric |The name to use for the metric.
|GangliaConstants.METRIC_NAME

|type |STRING |The type of value, see GMetricType javadoc for permitted
values. (Confluence not allowing the link) |GangliaConstants.METRIC_TYPE

|slope |BOTH |The slope, see GMetricSlope javadoc for permitted values.
(Confluence not allowing the link) |`GangliaConstants.METRIC_`SLOPE

|units |  |(optional) Any unit of measurement that qualifies the metric,
e.g. widgets, litres, bytes.  Do not include a prefix such as k (kilo)
or m (milli), other tools may scale the units later.  The value should
be unscaled. |`GangliaConstants.METRIC_UNITS`

|tmax |60 |Maximum time in seconds that the value can be considered
current.  After this, Ganglia considers the value to have expired.
|`GangliaConstants.METRIC_`TMAX

|dmax |0 |Minumum time in seconds before Ganglia will purge the metric
value if it expires.  Set to 0 and the value will remain in Ganglia
indefinitely until a gmond agent restart.
|`GangliaConstants.METRIC_`DMAX
|=======================================================================

[[Ganglia-Messagebody]]
Message body
~~~~~~~~~~~~

Any value (such as a string or numeric type) in the body is sent to the
Ganglia system.

[[Ganglia-Returnvalue/response]]
Return value / response
~~~~~~~~~~~~~~~~~~~~~~~

Ganglia sends metrics using unidirectional UDP or multicast.  There is
no response or change to the message body.

[[Ganglia-Examples]]
Examples
~~~~~~~~

[[Ganglia-SendingaStringmetric]]
Sending a String metric
^^^^^^^^^^^^^^^^^^^^^^^

The message body will be converted to a String and sent as a metric
value.  Unlike numeric metrics, String values can't be charted but
Ganglia makes them available for reporting.  The os_version string at
the top of every Ganglia host page is an example of a String metric.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:string.for.ganglia")
    .setHeader(GangliaConstants.METRIC_NAME, simple("my_string_metric"))
    .setHeader(GangliaConstants.METRIC_TYPE, GMetricType.STRING)
    .to("direct:ganglia.tx");

from("direct:ganglia.tx")
    .to("ganglia:239.2.11.71:8649?mode=MULTICAST&prefix=test");
----

[[Ganglia-Sendinganumericmetric]]
Sending a numeric metric
^^^^^^^^^^^^^^^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:value.for.ganglia")
    .setHeader(GangliaConstants.METRIC_NAME, simple("widgets_in_stock"))
    .setHeader(GangliaConstants.METRIC_TYPE, GMetricType.UINT32)
    .setHeader(GangliaConstants.METRIC_UNITS, simple("widgets"))
    .to("direct:ganglia.tx");

from("direct:ganglia.tx")
    .to("ganglia:239.2.11.71:8649?mode=MULTICAST&prefix=test");
----
