[[ConfluenceContent]]
*Camel-Gora* is an http://camel.apache.org/[Apache Camel] component that
allows you to work with NoSQL databases using the
http://gora.apache.org/[Apache Gora] framework.

*Available as of Camel 2.14*

Maven users will need to add the following dependency to their pom.xml
for this component:

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<dependency>
 <groupId>org.apache.camel</groupId>
 <artifactId>camel-gora</artifactId>
 <version>x.x.x</version>
 <!-- use the same version as your Camel core version -->
</dependency>
----

[[Gora-ApacheGoraOverview]]
Apache Gora Overview
~~~~~~~~~~~~~~~~~~~~

The http://gora.apache.org/[Apache Gora] open source framework provides
an in-memory data model and persistence for big data. Gora supports
persisting to column stores, key value stores, document stores and
RDBMSs, and analyzing the data with extensive
http://hadoop.apache.org/[Apache Hadoop™ MapReduce] support. Gora uses
the http://www.apache.org/licenses/LICENSE-2.0.html[Apache Software
License v2.0] and graduated from the Apache Incubator in Janauary 2012
to become a top-level Apache project.

Apache Gora currently supports the following datastores:
http://hbase.apache.org/[Apache HBase],
http://cassandra.apache.org/[Apache Cassandra],
http://accumulo.apache.org/[Apache Accumulo],
http://aws.amazon.com/dynamodb/[Amazon DynamoDB] and SQL databases such
as http://hsqldb.org/[hsqldb], http://www.mysql.com/[MySQL] and more.

[[Gora-URIformat]]
URI format
~~~~~~~~~~

[source,brush:,text;,gutter:,false;,theme:,Default]
----
gora:instanceName[?options]
----

Hbase examples with mandatory options :

_XML_

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<to uri="gora:foobar?keyClass=java.lang.Long&amp;valueClass=org.apache.camel.component.gora.generated.Pageview&amp;dataStoreClass=org.apache.gora.hbase.store.HBaseStore"/>
----

_Java DSL_

[source,brush:,java;,gutter:,false;,theme:,Default]
----
to("gora:foobar?keyClass=java.lang.Long&valueClass=org.apache.camel.component.gora.generated.Pageview&dataStoreClass=org.apache.gora.hbase.store.HBaseStore")
----

[[Gora-Configuratiion]]
Configuratiion
~~~~~~~~~~~~~~

Using camel-gora needs some configuration. This mainly involve to
configure the _AvroStore_ through the _gora.properties_ file and to
define the relevant mappings as part of the
_http://gora.apache.org/current/gora-core.html[gora-core]_ module.

Extensive information for this configuration can be found in the apache
http://gora.apache.org/current/index.html[gora documentation] and the
http://gora.apache.org/current/gora-conf.html[gora-conf] page.

[[Gora-SupportedGoraOperations]]
Supported Gora Operations
~~~~~~~~~~~~~~~~~~~~~~~~~

Supported operations include : _*put*, *get*, *delete*, *getSchemaName*,
*deleteSchema*, *createSchema*, *query*, *deleteByQuery*,
*schemaExists*_.

Some of the operations require arguments while some others no. The
arguments to operations could be either the _body_ of the _in_ message
or defined in a header property. Below there is a list with some
additional info for each operation.

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Property |Description
|put |_Inserts the persistent object with the given key._

|get |_Returns the object corresponding to the given key fetching all
the fields._

|delete |_Deletes the object with the given key._

|getSchemaName |_Returns the schema name given to this DataStore._

|deleteSchema |_Deletes the underlying schema or table (or similar) in
the datastore that holds the objects._

|createSchema |_Creates the optional schema or table (or similar) in the
datastore to hold the objects._

|query |_Executes the given query and returns the results._

|deleteByQuery |_Deletes all the objects matching the query._

|schemaExists |_Returns whether the schema that holds the data exists in
the datastore._
|=======================================================================

[[Gora-Options]]
Options
~~~~~~~

[[Gora-GoraHeaders]]
Gora Headers
^^^^^^^^^^^^

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Property |Description
|GoraOperation |_Used in order to define the operation to execute._

|GoraKey |_Used in order to define the datum key for the operations need
it._
|=======================================================================

[[Gora-GoraConfigurationattributes]]
Gora Configuration attributes
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Property |Type |Description
|keyClass |_String_ |_Key type._ *

|valueClass |_String_ |_Value type._ *

|dataStoreClass |_String_ |_DataStore type_ *

|hadoopConfiguration |_Configuration_ |_Hadoop Configuration_

|concurrentConsumers |_int_ |_Concurrent Consumers (used only by
consumers)._

|flushOnEveryOperation |_boolean_ |_Flush on every operation (used only
by producers)._
|=======================================================================

_NOTE: the gora configuration properties marked with asterisk are
mandatory_

[[Gora-GoraQueryattributes]]
Gora Query attributes
^^^^^^^^^^^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|===================================================
|Property |Type |Description
|startTime |_long_ |_Start Time attribute._
|endTime |_long_ |_End Time attribute._
|timeRangeFrom |_long_ |_Time Range From attribute._
|timeRangeTo |_long_ |_Time Range To attribute._
|limit |_long_ |_Gora Query Limit attribute._
|timestamp |_long_ |_Timestamp attribute._
|startKey |_Object_ |_Start Key attribute._
|endKey |_Object_ |_End Key attribute._
|keyRangeFrom |_Object_ |_Key Range From attribute._
|keyRangeTo |_Object_ |_Key Range To attribute._
|fields |_String_ |_Fields attribute._
|===================================================

[[Gora-Usageexamples]]
Usage examples
^^^^^^^^^^^^^^

*Create Schema* _(XML DSL)_:

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<setHeader headerName="GoraOperation">
 <constant>CreateSchema</constant>
</setHeader>
<to uri="gora:foobar?keyClass=java.lang.Long&amp;valueClass=org.apache.camel.component.gora.generated.Pageview&amp;dataStoreClass=org.apache.gora.hbase.store.HBaseStore"/>
----

*SchemaExists* _(XML DSL)_:

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<setHeader headerName="GoraOperation">
 <constant>SchemaExists</constant>
</setHeader>
 <to uri="gora:foobar?keyClass=java.lang.Long&amp;valueClass=org.apache.camel.component.gora.generated.Pageview&amp;dataStoreClass=org.apache.gora.hbase.store.HBaseStore"/>
----

*Put* _(XML DSL)_:

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<setHeader headerName="GoraOperation">
 <constant>put</constant>
</setHeader>
<setHeader headerName="GoraKey">
 <constant>22222</constant>
</setHeader>
<to uri="gora:foo?keyClass=java.lang.Long&amp;valueClass=org.apache.camel.component.gora.generated.Pageview&amp;dataStoreClass=org.apache.gora.hbase.store.HBaseStore"/>
----

*Get* _(XML DSL)_:

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<setHeader headerName="GoraOperation">
 <constant>GET</constant>
</setHeader>
<setHeader headerName="GoraKey">
 <constant>10101</constant>
</setHeader>
<to uri="gora:bar?keyClass=java.lang.Long&amp;valueClass=org.apache.camel.component.gora.generated.Pageview&amp;dataStoreClass=org.apache.gora.hbase.store.HBaseStore"/>
----

*Delete* _(XML DSL)_:

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<setHeader headerName="GoraOperation">
 <constant>DELETE</constant>
</setHeader>
<setHeader headerName="GoraKey">
 <constant>22222</constant>
</setHeader>
<to uri="gora:bar?keyClass=java.lang.Long&amp;valueClass=org.apache.camel.component.gora.generated.Pageview&amp;dataStoreClass=org.apache.gora.hbase.store.HBaseStore"/>
----

*Query* _(XML DSL)_:

[source,brush:,xml;,gutter:,false;,theme:,Default]
----
<to uri="gora:foobar?keyClass=java.lang.Long&amp;valueClass=org.apache.camel.component.gora.generated.Pageview&amp;dataStoreClass=org.apache.gora.hbase.store.HBaseStore"/>
----

The full usage examples in the form of integration tests can be found at
https://github.com/ipolyzos/camel-gora-examples/[camel-gora-examples]
repository.

[[Gora-Moreresources]]
More resources
^^^^^^^^^^^^^^

For more please information and in depth configuration refer to the
http://gora.apache.org/current/overview.html[Apache Gora Documentation]
and the http://gora.apache.org/current/tutorial.html[Apache Gora
Tutorial].
