[[ConfluenceContent]]
[[GuiceRunMavenGoal-guice:run]]
guice:run
~~~~~~~~~

The *guice:run* goal of the link:guice-maven-plugin.html[Guice Maven
Plugin] is used to run your Camel link:guice.html[Guice] configurations
in a forked JVM from Maven. A good example application to get you
started is the link:guice-jms-example.html[Guice JMS Example].

[source,brush:,java;,gutter:,false;,theme:,Default]
----
cd examples/camel-example-guice-jms
mvn guice:run
----

This makes it very easy to spin up and test your routing rules without
having to write a main(String[]) method; it also lets you create
multiple jars to host different sets of routing rules and easily test
them independently.

How this works is that the plugin will compile the source code in the
maven project, then boot up a Guice context using JNDI using the
*jndi.properties* file as described in the link:guice.html[guice
injection documentation].

This allows you to boot up any Guice services you wish; whether they are
Camel related or any other Guice POJOs.

If you want to boot up your Camel routes a little faster, you could try
the link:guice-embedded-maven-goal.html[guice:embedded] instead.
