[[ConfluenceContent]]
[[Hipchat-HipchatComponent]]
Hipchat Component
~~~~~~~~~~~~~~~~~

*Available as of Camel 2.15.0*

The Hipchat component supports producing and consuming messages from/to
https://www.hipchat.com[Hipchat] service.

[Info]
====
 **Prerequisites**

You must have a valid Hipchat user account and get a
https://www.hipchat.com/account/api[personal access token] that you can
use to produce/consume messages.

====

[[Hipchat-URIFormat]]
URI Format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
hipchat://[host][:port]?options
----

You can append query options to the URI in the following format,
?options=value&option2=value&...

[[Hipchat-URIOptions]]
URI Options
^^^^^^^^^^^

[width="99%",cols="20%,16%,16%,16%,16%,16%",options="header",]
|=======================================================================
|*Name* |*Default Value* |*Context* |*Required* |*Producer/Consumer*
|*Description*
|protocol |`null` |Shared |Yes |Both |Default protocol to connect to the
Hipchat server such as http or https

|host |null |Shared |Yes |Both |The API host of the Hipchat to connect
to, such as api.hipchat.com

|port |80 |Shared |No |Both |The port to connect to on the Hipchat host

|authToken |`null` |Shared |Yes |Both a|
Authorization token(personal access token) obtained from
https://www.hipchat.com/account/api[Hipchat]

 

|delay |5000 |Shared |No |Consumer |The poll interval in millisec for
consuming messages from consumeUsers provided. Please read about
https://www.hipchat.com/docs/apiv2/rate_limiting[rate limits] before
decreasing this.

|consumeUsers |`null` |Shared |No |Consumer |Comma separated list of
user @Mentions or emails whose messages to the owner of authToken must
be consumed
|=======================================================================

[[Hipchat-ScheduledPollConsumer]]
Scheduled Poll Consumer
^^^^^^^^^^^^^^^^^^^^^^^

This component implements the
link:polling-consumer.html[ScheduledPollConsumer]. Only the last message
from the provided 'consumeUsers' are retrieved and sent as Exchange
body. If you do not want the same message to be retrieved again when
there are no new messages on next poll then you can add the
link:idempotent-consumer.html[idempotent consumer] as shown below. All
the options on the link:polling-consumer.html[ScheduledPollConsumer] can
also be used for more control on the consumer.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
@Override
public void configure() throws Exception {
 String hipchatEndpointUri = "hipchat://?authToken=XXXX&consumeUsers=@Joe,@John";
 from(hipchatEndpointUri)
  .idempotentConsumer(
    simple("${in.header.HipchatMessageDate} ${in.header.HipchatFromUser}"),
    MemoryIdempotentRepository.memoryIdempotentRepository(200)
  )
  .to("mock:result");
}
----

[[Hipchat-MessageheaderssetbytheHipchatconsumer]]
Message headers set by the Hipchat consumer
+++++++++++++++++++++++++++++++++++++++++++

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|*Header* |*Constant* |*Type* |*Description*
|HipchatFromUser |HipchatConstants.FROM_USER |_String_ |The body has the
message that was sent from this user to the owner of authToken

|HipchatMessageDate |HipchatConstants.MESSAGE_DATE |_String_ |The date
message was sent. The format is ISO-8601 as present in the Hipchat
https://www.hipchat.com/docs/apiv2/method/view_recent_privatechat_history[response].

|HipchatFromUserResponseStatus
|HipchatConstants.FROM_USER_RESPONSE_STATUS 
|_http://hc.apache.org/httpcomponents-core-4.2.x/httpcore/apidocs/org/apache/http/StatusLine.html[StatusLine]_
|The status of the API response received.
|=======================================================================

[[Hipchat-HipchatProducer]]
Hipchat Producer
^^^^^^^^^^^^^^^^

Producer can send messages to both Room's and User's simultaneously. The
body of the exchange is sent as message. Sample usage is shown below.
Appropriate headers needs to be set.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
@Override
 public void configure() throws Exception {
  String hipchatEndpointUri = "hipchat://?authToken=XXXX";
  from("direct:start")
   .to(hipchatEndpointUri)
   .to("mock:result");
 }
----

[[Hipchat-MessageheadersevaluatedbytheHipchatproducer]]
Message headers evaluated by the Hipchat producer
+++++++++++++++++++++++++++++++++++++++++++++++++

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|*Header* |*Constant* |*Type* |*Description*
|HipchatToUser |HipchatConstants.TO_USER |_String_ |The Hipchat user to
which the message needs to be sent.

|HipchatToRoom |HipchatConstants.TO_ROOM |_String_ |The Hipchat room to
which the message needs to be sent.

|HipchatMessageFormat |HipchatConstants.MESSAGE_FORMAT |String |Valid
formats are 'text' or 'html'. *Default: 'text'*

|HipchatMessageBackgroundColor
|HipchatConstants.MESSAGE_BACKGROUND_COLOR |_String_ |Valid color values
are 'yellow', 'green', 'red', 'purple', 'gray', 'random'. *Default:
'yellow' (Room Only)* 

|HipchatTriggerNotification |HipchatConstants.TRIGGER_NOTIFY |_String_
|Valid values are 'true' or 'false'. Whether this message should trigger
a user notification (change the tab color, play a sound, notify mobile
phones, etc). *Default: 'false' (Room Only)*
|=======================================================================

[[Hipchat-MessageheaderssetbytheHipchatproducer]]
Message headers set by the Hipchat producer
+++++++++++++++++++++++++++++++++++++++++++

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|*Header* |*Constant* |*Type* |*Description*
|HipchatToUserResponseStatus |HipchatConstants.TO_USER_RESPONSE_STATUS
|_http://hc.apache.org/httpcomponents-core-4.2.x/httpcore/apidocs/org/apache/http/StatusLine.html[StatusLine]_
|The status of the API response received when message sent to the user.

|HipchatFromUserResponseStatus |HipchatConstants.TO_ROOM_RESPONSE_STATUS
|_http://hc.apache.org/httpcomponents-core-4.2.x/httpcore/apidocs/org/apache/http/StatusLine.html[StatusLine]_
|The status of the API response received when message sent to the room.
|=======================================================================

[[Hipchat-Dependencies]]
Dependencies
++++++++++++

Maven users will need to add the following dependency to their pom.xml.

*pom.xml*

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-hipchat</artifactId>
    <version>${camel-version}</version>
</dependency>
----

where `${camel-version`} must be replaced by the actual version of Camel
(2.15.0 or higher)
