[[ConfluenceContent]]
[[HowdoIconfigurethemaximumendpointcachesizeforCamelContext-HowdoIconfigurethemaximumendpointcachesizeforCamelContext?]]
How do I configure the maximum endpoint cache size for CamelContext?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

link:camelcontext.html[CamelContext] will by default cache the last 1000
used endpoints (based on a LRUCache).

[[HowdoIconfigurethemaximumendpointcachesizeforCamelContext-Configuringcachesize]]
Configuring cache size
^^^^^^^^^^^^^^^^^^^^^^

*Available as of Camel 2.8*

You can configure the default maximum cache size by setting the
`Exchange.MAXIMUM_ENDPOINT_CACHE_SIZE` property on
link:camelcontext.html[CamelContext].

[source,brush:,java;,gutter:,false;,theme:,Default]
----
getCamelContext().getProperties().put(Exchange.MAXIMUM_ENDPOINT_CACHE_SIZE, "500");
----

You need to configure this before link:camelcontext.html[CamelContext]
is started.

And in Spring XML its done as:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<camelContext>
   <properties>
      <property key="CamelMaximumEndpointCacheSize" value="500"/>
   </properties>
...
</camelContext>
----

At runtime you can see the `EndpointRegistry` in JMX as they are listed
in the `services` category.

[[HowdoIconfigurethemaximumendpointcachesizeforCamelContext-SeeAlso]]
See Also
^^^^^^^^

* link:how-do-i-configure-the-default-maximum-cache-size-for-producercache-or-producertemplate.html[How
do I configure the default maximum cache size for ProducerCache or
ProducerTemplate]
