[[ConfluenceContent]]
[[Howtosendthesamemessagetomultipleendpoints-Howtosendthesamemessagetomultipleendpoints]]
How to send the same message to multiple endpoints
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When you need to send the *same* message to multiple endpoints then you
should use link:multicast.html[Multicast].

In the sample below we consume messages from the activemq queue `foo`
and want to send the *same message* to both `seda:foo` and `seda:bar`.
Sending the same message requires that we use
link:multicast.html[Multicast]. This is done by adding the `multicast()`
before the to type:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("activemq:queue:foo").multicast().to("seda:foo", "seda:bar");
----

**Pipeline is default in Camel**

If you have a route such as:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("activemq:queue:foo").to("seda:foo", "seda:bar");
----

It is default a link:pipes-and-filters.html[pipeline] in Camel (that is
the opposite to link:multicast.html[Multicast]). In the above example
using pipes and filters then the result from seda:foo is sent to
seda:bar, ie. its not the *same* message sent to multiple destinations,
but a sent through a chain (the pipes and the filters).
