[[ConfluenceContent]]
[[HowdoIeditthewebsite-HowdoIeditthewebsite?]]
How do I edit the website?
~~~~~~~~~~~~~~~~~~~~~~~~~~

The website is all contained on a Wiki so that you can
link:contributing.html[contribute] providing you are happy to license
all your contributions under the
http://www.apache.org/licenses/LICENSE-2.0[Apache Software License
version 2.0]

[[HowdoIeditthewebsite-YoumusthavesignedanICLAtobeabletoeditthewikipages]]
You must have signed an ICLA to be able to edit the wiki pages
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Download and print the Apache Contributor License Agreement from
http://www.apache.org/dev/new-committers-guide.html[here]. You need to
sign it and fax it to Apache. In the past I've found its often faster to
also post it via snail mail
* wait for your name to appear on the
http://people.apache.org/unlistedclas.html[list of received CLAs] see
the _unlisted CLAs_ section.
* send an email to the link:mailing-lists.html[Camel dev forum] about
that your ICLA have been received at Apache, and include your
*wiki* *username* in the email.
* A Camel PMC member will then verify that ASF have received the ICLA
and assign edit rights to your username, using
https://cwiki.apache.org/confluence/spaces/spacepermissions.action?key=CAMEL[this
page].

[[HowdoIeditthewebsite-Howtoedit]]
How to edit
^^^^^^^^^^^

To edit a page, just hit the *edit* link right at the bottom of any
page. To be able to edit you need to register with confluence.

[Info]
====
 **Spam Prevention**

We have been attacked by spammers so we are running a spam-avoiding
scheme. So you have to ask to be added to the editing group of
Confluence. This is quick and easy to do.

First click edit on a page to get to the confluence site of
http://cwiki.apache.org/confluence/display/CAMEL/Index then register.

Then send an mail to the
http://www.nabble.com/Camel-Development-f36429.html[developer forum]
giving details of your confluence and/or JIRA username and we can grant
you the necessary editing karma.

====

Note that after you've changed the wiki it is immediately rendered on
the http://cwiki.apache.org/CAMEL/ site so you can test it out; then up
to an hour or two later it is updated on the Apache site.

[[HowdoIeditthewebsite-Howthesiteworks]]
How the site works
^^^^^^^^^^^^^^^^^^

There are a few special pages; for example the
link:navigation.html[Navigation] page is the right hand navigation bar
and the link:quicklinks.html[QuickLinks] is the top right navigation
bar.

Other useful link:site.html[links] are

This page contains the main navigation links to the parts which make up
the Site layout.

* link:banner.html[Banner]
* link:book.html[Book]
* link:book-in-one-page.html[Book In One Page]
* link:includes.html[Includes]
* link:navigation.html[Navigation]
* link:quicklinks.html[QuickLinks]
* link:scratch-page.html[Scratch Page]
* link:siteindex.html[SiteIndex]
* link:sitemap.html[SiteMap]
* link:site-update-ideas.html[Site Update Ideas]
