[[ConfluenceContent]]
[Tip]
====
 **Available since Camel 2.17.0**

  ====

 

The IronMQ component provides integration with
http://www.iron.io/products/mq[IronMQ] a elastic and durable hosted
message queue as a service.

The component uses the https://github.com/iron-io/iron_mq_java[IronMQ
java client] library.

To run it requires a IronMQ account, and a project id and token.

 

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-ironmq</artifactId>
    <!-- use the same version as your Camel core version -->
    <version>x.y.z</version>
</dependency>
----

[[IronMQ-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
ironmq:queueName[?options]
----

Where *queueName* identifies the IronMQ queue you want to publish or
consume messages from.

[[IronMQ-Options]]
Options
^^^^^^^

[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|=======================================================================
|Name |Group |Default |Type |Description
|*client* |common |null |io.iron.ironmq.Client |Reference to a
io.iron.ironmq.Client in the Registry.

|*ironMQCloud* |common |https://mq-aws-us-east-1-1.iron.io |String
|IronMq Cloud url. Urls for public clusters:
https://mq-aws-http://us-east-1-1.iron.io[us-east-1-1.iron.io] (US),
https://mq-aws-eu-http://west-1-1.iron.io[west-1-1.iron.io] (EU)

|*preserveHeaders* |common |false |boolean a|
Should message headers be preserved when publishing messages.

This will add the Camel headers to the Iron MQ message as a json payload
with a header list, and a message body.

Useful when Camel is both consumer and producer.

|*projectId* |common |null |String |The IronMQ project Id

|*token* |common |null |String |The IronMQ token

|*batchDelete* |consumer |false |boolean |Should messages be deleted in
one batch. This will limit the number of api requests since messages are
deleted in one request, instead of one pr. exchange. If enabled care
should be taken that the consumer is idempotent when processing
exchanges.

|*concurrentConsumers* |consumer |1 |int |The number of concurrent
consumers.

|*maxMessagesPerPoll* |consumer |1 |int |Number of messages to poll pr.
call. Maximum is 100.

|*timeout* |consumer |60 |int |After timeout (in seconds), item will be
placed back onto the queue.

|*wait* |consumer |0 |int |Time in seconds to wait for a message to
become available. This enables long polling. Default is 0 (does not
wait), maximum is 30.

|*visibilityDelay* |producer |0 |int |The item will not be available on
the queue until this many seconds have passed. Default is 0 seconds.
|=======================================================================

[[IronMQ-Producerheaders]]
Producer headers
^^^^^^^^^^^^^^^^

[cols=",,",options="header",]
|=======================================================================
|Header |Type |Description
|CamelIronMQOperation |String |If value set to __CamelIronMQClearQueue__
the queue is cleared of unconsumed messages.

|CamelIronMQMessageId |String or io.iron.ironmq.Ids |The id of the
IronMQ message as a String when sending a single message, or a Ids
object when sending a array of strings. See message body
|=======================================================================

[[IronMQ-Consumerheaders]]
Consumer headers
^^^^^^^^^^^^^^^^

[cols=",,",options="header",]
|=======================================================================
|Header |Type |Description
|CamelIronMQMessageId |String |The id of the message.

|CamelIronMQReservationId |String |The reservation id of the message.

|CamelIronMQReservedCount |String |The number of times this message has
been reserved.
|=======================================================================

[[IronMQ-Messagebodywhenproducing]]
Message body when producing
^^^^^^^^^^^^^^^^^^^^^^^^^^^

Should be either a String or a array of Strings.

In the latter case the batch of strings will be send to IronMQ as one
request, creating one message pr. element in the array.

[[IronMQ-Consumerexample]]
Consumer example
^^^^^^^^^^^^^^^^

Consume 50 messages pr. poll from the queue 'testqueue' on aws eu, and
save the messages to files.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("ironmq:testqueue?ironMQCloud=https://mq-aws-eu-west-1-1.iron.io&projectId=myIronMQProjectid&token=myIronMQToken&maxMessagesPerPoll=50")
  .to("file:somefolder");
----

[[IronMQ-Producerexample]]
Producer example
^^^^^^^^^^^^^^^^

Dequeue from activemq jms and enqueue the messages on IronMQ.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("activemq:foo")
  .to("ironmq:testqueue?projectId=myIronMQProjectid&token=myIronMQToken");
----
