[[ConfluenceContent]]
[[Jing-JingComponent]]
Jing Component
~~~~~~~~~~~~~~

The Jing component uses the
http://www.thaiopensource.com/relaxng/jing.html[Jing Library] to perform
XML validation of the message body using either

* http://relaxng.org/[RelaxNG XML Syntax]
* http://relaxng.org/compact-tutorial-20030326.html[RelaxNG Compact
Syntax]

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-jing</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

Note that the link:msv.html[MSV] component can also support RelaxNG XML
syntax.

[[Jing-URIformatCamel2.15orolder]]
URI format Camel 2.15 or older
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
rng:someLocalOrRemoteResource
rnc:someLocalOrRemoteResource
----

Where *rng* means use the http://relaxng.org/[RelaxNG XML Syntax]
whereas *rnc* means use
http://relaxng.org/compact-tutorial-20030326.html[RelaxNG Compact
Syntax]. The following examples show possible URI values

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Example |Description
|rng:foo/bar.rng |References the XML file *foo/bar.rng* on the classpath
a|
rnc:

http://foo.com/bar.rnc

 a|
References the RelaxNG Compact Syntax file from the URL,

http://foo.com/bar.rnc

|=======================================================================

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[Jing-URIformatCamel2.16]]
URI format Camel 2.16
^^^^^^^^^^^^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
jing:someLocalOrRemoteResource
----

From Camel 2.16 the component use jing as name, and you can use the
option compactSyntax to turn on either RNG or RNC mode.

[[Jing-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Option |Default |Description
|compactSyntax |`false` |Whether to validate using RelaxNG compact
syntax or not.
|=======================================================================

[[Jing-Example]]
Example
^^^^^^^

The following
http://svn.apache.org/repos/asf/camel/trunk/components/camel-jing/src/test/resources/org/apache/camel/component/validator/jing/rnc-context.xml[example]
shows how to configure a route from the endpoint *direct:start* which
then goes to one of two endpoints, either *mock:valid* or *mock:invalid*
based on whether or not the XML matches the given
http://relaxng.org/compact-tutorial-20030326.html[RelaxNG Compact
Syntax] schema (which is supplied on the classpath).

[[Jing-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]
