[[ConfluenceContent]]
[[JIRA-JIRA]]
JIRA
~~~~

*Available as of Camel 2.15*

The JIRA component interacts with the JIRA API by encapsulating
Atlassian's https://marketplace.atlassian.com/plugins/com.atlassian.jira.jira-rest-java-client[REST
Java Client for JIRA]. It currently provides polling for new issues and
new comments.  It is also able to create new issues.

Rather than webhooks, this endpoint relies on simple polling. Reasons
include:

* Concern for reliability/stability
* The types of payloads we're polling aren't typically large (plus,
paging is available in the API)
* The need to support apps running somewhere not publicly accessible
where a webhook would fail

Note that the JIRA API is fairly expansive.  Therefore, this component
could be easily expanded to provide additional interactions.

Maven users will need to add the following dependency to their pom.xml
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-jira</artifactId>
    <version>${camel-version}</version>
</dependency>
----

[[JIRA-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,text;,gutter:,false;,theme:,Default]
----
jira://endpoint[?options]
----

[[JIRA-MandatoryOptions:]]
Mandatory Options:
^^^^^^^^^^^^^^^^^^

Note that these can be configured directly through the endpoint.

[width="100%",cols="50%,50%",options="header",]
|===============================
|Option |Description
|serverUrl |JIRA host server URL
|username |JIRA username
|password |JIRA password
|===============================

[[JIRA-ConsumerEndpoints:]]
Consumer Endpoints:
^^^^^^^^^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|===================================================================
|Endpoint |Context |Body Type
|newIssue |polling |com.atlassian.jira.rest.client.domain.BasicIssue
|newComment |polling |com.atlassian.jira.rest.client.domain.Comment
|===================================================================

[[JIRA-ProducerEndpoints:]]
Producer Endpoints:
^^^^^^^^^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Endpoint |Body |Required Message Headers
|pullRequestComment |String (issue description) a|
* ProjectKey (String): The project key
* IssueTypeId (long): The issue type id (ex: "Bug" is typically 1 in
most default configs)
* IssueSummary (String): The issue summary (title)

|=======================================================================

[[JIRA-URIOptions:]]
URI Options:
^^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|========================================================
|Name |Default Value |Description
|delay |`60` |in seconds
|jql |  |Used by the consumer endpoints. More info below.
|========================================================

[[JIRA-JQL:]]
JQL:
^^^^

The JQL URI option is used by both consumer endpoints.  Theoretically,
items like "project key", etc. could be URI options themselves.
 However, by requiring the use of JQL, the consumers become much more
flexible and powerful.

At the bare minimum, the consumers will require the following:

[source,brush:,text;,gutter:,false;,theme:,Default]
----
jira://[endpoint]?[required options]&jql=project=[project key]
----

One important thing to note is that the newIssue consumer will
automatically append "ORDER BY key desc" to your JQL.  This is in order
to optimize startup processing, rather than having to index every single
issue in the project.

Another note is that, similarly, the newComment consumer will have to
index every single issue *and* comment in the project.  Therefore, for
large projects, it's *vital* to optimize the JQL expression as much as
possible.  For example, the JIRA Toolkit Plugin includes a "Number of
comments" custom field -- use '"Number of comments" > 0' in your query.
Also try to minimize based on state (status=Open), increase the polling
delay, etc.  Example:

[source,brush:,text;,gutter:,false;,theme:,Default]
----
jira://[endpoint]?[required options]&jql=RAW(project=[project key] AND status in (Open, \"Coding In Progress\") AND \"Number of comments\">0)"
----
