[[ConfluenceContent]]
[[Paho-PahoComponent]]
Paho Component
~~~~~~~~~~~~~~

 

[Info]
====


Available as of Camel 2.16 

====

Paho component provides connector for the MQTT messaging protocol using
the https://eclipse.org/paho/[Eclipse Paho] library. Paho is one of the
most popular MQTT libraries, so if you would like to integrate it with
your Java project - Camel Paho connector is a way to go.

[[Paho-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
paho:queueName[?options]
----

For example the following snippet reads messages from the MQTT broker
installed on the same host as the Camel router:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("paho:some/queue").
  to("mock:test");
----

While the snippet below sends message to the MQTT broker:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:test").
  to("paho:some/target/queue");
----

You can append query options to the URI in the following
format: `?option=value&option=value&...` . For example this is how
to read messages from the remote MQTT broker: 

 

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("paho:some/queue?brokerUrl=tcp://iot.eclipse.org:1883").
  to("mock:test");
----

 

[[Paho-Addingthecomponenttotheproject]]
Adding the component to the project
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-paho</artifactId>
    <version>x.y.z</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

Keep in mind that Paho artifacts are not hosted in the Maven Central, so
you need to add Eclipse Paho repository to your POM xml file:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<repositories>
  <repository>
    <id>eclipse-paho</id>
    <url>https://repo.eclipse.org/content/repositories/paho-releases</url>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </repository>
</repositories>
----

[[Paho-Defaultpayloadtype]]
Default payload type
^^^^^^^^^^^^^^^^^^^^

 

By default Camel Paho component operates on the binary payloads
extracted out of (or put into) the MQTT message:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
// Receive payload
byte[] payload = (byte[]) consumerTemplate.receiveBody("paho:topic");
 
// Send payload
byte[] payload = "message".getBytes();
producerTemplate.sendBody("paho:topic", payload);
----

 

But of course Camel build-in link:type-converter.html[type conversion
API] can perform the automatic data type transformations for you. In the
example below Camel automatically converts binary payload into String
(and conversely):

 

[source,brush:,java;,gutter:,false;,theme:,Default]
----
// Receive payload
String payload = consumerTemplate.receiveBody("paho:topic", String.class);
 
// Send payload
String payload = "message";
producerTemplate.sendBody("paho:topic", payload);
----

 +

[[Paho-URIOptions]]
URI Options
^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Option |Default |Description
|`clientId` |`camel-<timestamp>` |MQTT client identifier.

|`brokerUrl` |`tcp://localhost:1883` |The URL of the MQTT broker.

|`persistence` |`memory` |Client persistence to be used - `memory` or
`file`.

|`filePersistenceDirectory` |current directory |*(Camel 2.16.1 and
2.17)* Base directory used by file persistence. Takes no effect if
non-file persistence is used.

|`qos` |2 |Client quality of service level (`0`-`2`).

|`connectOptions` |none |The reference to the
`org.eclipse.paho.client.mqttv3.MqttConnectOptions` instance located in
the Camel registry. Referenced `MqttConnectOptions` instance will be
used by the endpoint to initialize the connection. For example
`connectOptions=#my``ConnectOptions` notation can be used to reference
Spring bean named `my`ConnectOptions. If there is only a single instance
of the `MqttConnectOptions` in the registry, it will be automatically
picked up by the endpoint.
|=======================================================================

For example the convention-over-configuration approach used in Camel is
really handy for the most of the situations, but sometimes you would
like to have more fine-grained control over the MQTT client connection.
To cover such situations just add the bean of type
`org.eclipse.paho.client.mqttv3.MqttConnectOptions` to your
link:registry.html[Camel registry]. For Spring applications that would
means adding bean to your application context. The snippet below uses
password-based authentication to connect to the MQTT broker:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
@Bean
MqttConnectOptions connectOptions() {
  MqttConnectOptions connectOptions = new MqttConnectOptions();
  connectOptions.setUserName("henry");
  connectOptions.setPassword("secret".toCharArray());
  return connectOptions;
}
----

 +

[[Paho-Headers]]
Headers
^^^^^^^

The following headers are recognized by the Paho component:

[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|=======================================================================
|Header |Java constant |Endpoint type |Value type |Description
|`PahoOriginalMessage` |`PahoConstants.HEADER_ORIGINAL_MESSAGE`
|Consumer |`org.eclipse.paho.client.mqttv3.MqttMessage` a|
The original Paho message instance received by the client.

*Deprecated:* from Camel 2.17 onwards the original MqttMessage is not
stored as a header but on the
`org.apache.camel.component.paho.PahoMessage` message that has a getter
`getMqttMessage`.

|`CamelMqttTopic` |PahoConstants.MQTT_TOPIC |Consumer |String |**Camel
2.17:**The topic
|=======================================================================

 

[[Paho-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]
