[[ConfluenceContent]]
[[Predicate-Predicates]]
Predicates
~~~~~~~~~~

Camel supports a pluggable interface called
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Predicate.html[Predicate]
which can be used to integrate a dynamic predicate into
link:enterprise-integration-patterns.html[Enterprise Integration
Patterns] such as when using the link:message-filter.html[Message
Filter] or link:content-based-router.html[Content Based Router].

A Predicate is being evaluated to a boolean value so the result is
either `true` or `false`. This makes link:predicate.html[Predicate] so
powerful as it is often used to control the routing of message in which
path they should be routed.

A simple example is to route an link:exchange.html[Exchange] based on a
header value:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("jms:queue:order")
   .choice()
      .when(header("type").isEqualTo("widget")).to("bean:widgetOrder")
      .when(header("type").isEqualTo("wombat")).to("bean:wombatOrder")
   .otherwise()
      .to("bean:miscOrder")
   .end();  
----

In the route above the link:predicate.html[Predicate] is the
`header("type").isEqualTo("widget")` as its constructed as an
link:expression.html[Expression] that is evaluated as a
link:predicate.html[Predicate]. To do this the various Builder classes
helps us here to create a nice and fluent syntax. `isEqualTo` is a
builder method that returns a link:predicate.html[Predicate] based on
the input.

Sometimes the fluent builders can get long and a bit complex to read,
then you can just define your predicate outside the route and then just
refer to the predicate in the route:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
Predicate isWidget = header("type").isEqualTo("widget");
----

And then you can refer to it in the route as:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("jms:queue:order")
   .choice()
      .when(isWidget).to("bean:widgetOrder")
      .when(isWombat).to("bean:wombatOrder")
   .otherwise()
      .to("bean:miscOrder")
   .end();  
----

[[Predicate-NegatingaPredicate]]
Negating a Predicate
++++++++++++++++++++

You can use the *not* method on the `PredicateBuilder` to negate a
predicate.

First we import the not static, so it makes our route nice and easy to
read:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
import static org.apache.camel.builder.PredicateBuilder.not
----

And then we can use it to enclose an existing predicate and negate it as
the example shows:

[[Predicate-CompoundPredicates]]
Compound Predicates
^^^^^^^^^^^^^^^^^^^

You can also create compound predicates using boolean operators such as
`and, or, not` and many others.

Currently this feature is only available in the Java-based DSLs, but not
in the Spring nor Blueprint DSLs.

Using the
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/builder/PredicateBuilder.html[`PredicateBuilder`]
class, you can combine predicates *from different Expression Languages*
based on logical operators and comparison operators:

* `not`, `and`, `or`
* `isNull`, `isNotNull`
* `isEqualTo`, `isGreaterThan`, `isLessThan`
* `startsWith`, `endsWith`
* `in` ("any of X predicates stands true")

Additionally, with `PredicateBuilder` you can create Regular Expressions
and use them as predicates, applying them to the result of an
expression, e.g. `PredicateBuilder.regex(header("foo"), "\d{4}")`
applies the regular expression to the header = foo.

Combining different Expression Languages is also possible, e.g.:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
PredicateBuilder.and(XPathBuilder.xpath("/bookings/flights"), simple("${property.country = 'Spain'}"))
----

The sample below demonstrates further use cases:

[[Predicate-ExtensiblePredicates]]
Extensible Predicates
^^^^^^^^^^^^^^^^^^^^^

Camel supports extensible Predicates using multiple
link:languages.html[Languages]; the following languages are supported
out of the box

* link:bean-language.html[Bean Language] for using Java for expressions
* link:constant.html[Constant]
* the unified link:el.html[EL] from JSP and JSF
* link:header.html[Header]
* link:jsonpath.html[JSonPath]
* link:jxpath.html[JXPath]
* link:mvel.html[Mvel]
* link:ognl.html[OGNL]
* link:ref-language.html[Ref Language]
* link:exchangeproperty.html[ExchangeProperty]
/ link:property.html[Property]
* link:scripting-languages.html[Scripting Languages] such as
** link:beanshell.html[BeanShell]
** link:javascript.html[JavaScript]
** link:groovy.html[Groovy]
** link:python.html[Python]
** link:php.html[PHP]
** link:ruby.html[Ruby]
* link:simple.html[Simple]
** link:file-language.html[File Language]
* link:spel.html[Spring Expression Language]
* link:sql.html[SQL]
* link:tokenizer.html[Tokenizer]
* link:xpath.html[XPath]
* link:xquery.html[XQuery]
* link:vtd-xml.html[VTD-XML]

Most of these languages is also supported used as
link:annotation-based-expression-language.html[Annotation Based
Expression Language].

You can easily write your own plugin predicate by implementing the
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Predicate.html[Predicate
interface].

There are also a number of helper builders available such as the
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/builder/PredicateBuilder.html[PredicateBuilder
class]

[[Predicate-UsingPredicatesinyourIDE]]
Using Predicates in your IDE
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To use different expression and predicates in your IDE you need to
perform a static import of the builder class for the language(s) you
wish to use.

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Language(s) |Builder class to import
|link:scripting-languages.html[Scripting Languages] such as
link:beanshell.html[BeanShell], link:javascript.html[JavaScript],
link:groovy.html[Groovy], link:php.html[PHP], link:python.html[Python]
and link:ruby.html[Ruby]
|http://camel.apache.org/maven/current/camel-script/apidocs/org/apache/camel/builder/script/ScriptBuilder.html[org.apache.camel.builder.script.ScriptBuilder]

|link:sql.html[SQL]
|http://camel.apache.org/maven/current/camel-josql/apidocs/org/apache/camel/builder/sql/SqlBuilder.html[org.apache.camel.builder.josql.SqlBuilder]

|link:xpath.html[XPath]
|http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/builder/xml/XPathBuilder.html[org.apache.camel.builder.xml.XPathBuilder]

|link:xquery.html[XQuery]
|http://camel.apache.org/maven/current/camel-saxon/apidocs/org/apache/camel/builder/saxon/XQueryBuilder.html[org.apache.camel.builder.saxon.XQueryBuilder]
|=======================================================================

[[Predicate-SeeAlso]]
See Also
++++++++

* link:expression.html[Expression]
