[[ConfluenceContent]]
[[Printer-PrinterComponent]]
Printer Component
~~~~~~~~~~~~~~~~~

*Available as of Camel 2.1*

The *printer* component provides a way to direct payloads on a route to
a printer. Obviously the payload has to be a formatted piece of payload
in order for the component to appropriately print it. The objective is
to be able to direct specific payloads as jobs to a line printer in a
camel flow.

This component only supports a camel producer endpoint.

The functionality allows for the payload to be printed on a default
printer, named local, remote or wirelessly linked printer using the
javax printing API under the covers.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-printer</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

[[Printer-URIformat]]
URI format
^^^^^^^^^^

Since the URI scheme for a printer has not been standardized (the
nearest thing to a standard being the IETF print standard) and therefore
not uniformly applied by vendors, we have chosen *"lpr"* as the scheme.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
lpr://localhost/default[?options]
lpr://remotehost:port/path/to/printer[?options]
----

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[Printer-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|`mediaSize` |`NA_LETTER` |Sets the stationary as defined by enumeration
names in the
http://download.oracle.com/javase/6/docs/api/javax/print/attribute/standard/MediaSizeName.html[javax.print.attribute.standard.MediaSizeName
API]. The default setting is to use North American Letter sized
stationary. The value's case is ignored, e.g. values of `iso_a4` and
`ISO_A4` may be used.

|`copies` |`1` |Sets number of copies based on the
javax.print.attribute.standard.Copies API

|`sides` |`Sides.ONE_SIDED` |Sets one sided or two sided printing based
on the javax.print.attribute.standard.Sides API

|`flavor` |`DocFlavor.BYTE_ARRAY` |Sets DocFlavor based on the
javax.print.DocFlavor API

|`mimeType` |`AUTOSENSE` |Sets mimeTypes supported by the
javax.print.DocFlavor API

|`mediaTray` |`AUTOSENSE` |Since *Camel 2.11.x* sets MediaTray supported
by the javax.print.DocFlavor API

|`printerPrefix` |null |Since *Camel 2.11.x* sets the prefix name of the
printer, it is useful when the printer name does not start with
//hostname/printer

|`sendToPrinter` |true |Setting this option to `false` prevents sending
of the
http://docs.oracle.com/javase/6/docs/api/javax/print/Doc.html[print
data] to the printer

|`orientation` |`portrait` |Since *Camel 2.13.x* Sets the page
orientation. Possible values: `portrait`, `landscape`,
`reverse-portrait` or `reverse-landscape`, based on
`javax.print.attribute.standard.OrientationRequested`
|=======================================================================

[[Printer-SendingMessagestoaPrinter]]
Sending Messages to a Printer
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[[Printer-PrinterProducer]]
Printer Producer
++++++++++++++++

Sending data to the printer is very straightforward and involves
creating a producer endpoint that can be sent message exchanges on in
route.

[[Printer-UsageSamples]]
Usage Samples
^^^^^^^^^^^^^

[[Printer-Example1:PrintingtextbasedpayloadsonaDefaultprinterusingletterstationaryandone-sidedmode]]
Example 1: Printing text based payloads on a Default printer using
letter stationary and one-sided mode
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[source,brush:,java;,gutter:,false;,theme:,Default]
----
RouteBuilder builder = new RouteBuilder() {
    public void configure() {
       from(file://inputdir/?delete=true)
       .to("lpr://localhost/default?copies=2" +
           "&flavor=DocFlavor.INPUT_STREAM&" +
           "&mimeType=AUTOSENSE" +
           "&mediaSize=NA_LETTER" +
           "&sides=one-sided")
    }};
----

[[Printer-Example2:PrintingGIFbasedpayloadsonaRemoteprinterusingA4stationaryandone-sidedmode]]
Example 2: Printing GIF based payloads on a Remote printer using A4
stationary and one-sided mode
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[source,brush:,java;,gutter:,false;,theme:,Default]
----
RouteBuilder builder = new RouteBuilder() {
    public void configure() {
       from(file://inputdir/?delete=true)
       .to("lpr://remotehost/sales/salesprinter" +
           "?copies=2&sides=one-sided" +
           "&mimeType=GIF&mediaSize=ISO_A4" +
           "&flavor=DocFlavor.INPUT_STREAM")
   }};
----

[[Printer-Example3:PrintingJPEGbasedpayloadsonaRemoteprinterusingJapanesePostcardstationaryandone-sidedmode]]
Example 3: Printing JPEG based payloads on a Remote printer using
Japanese Postcard stationary and one-sided mode
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[source,brush:,java;,gutter:,false;,theme:,Default]
----
RouteBuilder builder = new RouteBuilder() {
    public void configure() {
       from(file://inputdir/?delete=true)
       .to("lpr://remotehost/sales/salesprinter" +
           "?copies=2&sides=one-sided" +
           "&mimeType=JPEG" +
           "&mediaSize=JAPANESE_POSTCARD" +
           "&flavor=DocFlavor.INPUT_STREAM")
    }};
----
