[[ConfluenceContent]]
[[Quartz2-Quartz2Component]]
Quartz2 Component
~~~~~~~~~~~~~~~~~

*Available as of Camel 2.12.0*

The *quartz2:* component provides a scheduled delivery of messages using
the http://www.quartz-scheduler.org/[Quartz Scheduler 2.x]. +
Each endpoint represents a different timer (in Quartz terms, a Trigger
and JobDetail).

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-quartz2</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

*NOTE:* Quartz 2.x API is not compatible with Quartz 1.x. If you need to
remain on old Quartz 1.x, please +
use the old link:quartz.html[Quartz] component instead.

[[Quartz2-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
quartz2://timerName?options
quartz2://groupName/timerName?options
quartz2://groupName/timerName?cron=expression
quartz2://timerName?cron=expression
----

The component uses either a `CronTrigger` or a `SimpleTrigger`. If no
cron expression is provided, the component uses a simple trigger. If no
`groupName` is provided, the quartz component uses the `Camel` group
name.

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[Quartz2-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Parameter |Default |Description
|`cron` |_None_ |Specifies a `cron` expression (not compatible with the
`trigger.*` or `job.*` options).

|`trigger.repeatCount` |`0` |SimpleTrigger: How many times should the
timer repeat?

|`trigger.repeatInterval` |`1000` |SimpleTrigger: The amount of time in
milliseconds between repeated triggers. Must enable
`trigger.repeatCount` to use the simple trigger using this interval.

|`job.name` |`null` |Sets the job name.

|`job.XXX` |`null` |Sets the job option with the `XXX` setter name.

|`trigger.XXX` |`null` |Sets the trigger option with the `XXX` setter
name.

|`stateful` |`false` |Uses a Quartz `@PersistJobDataAfterExecution` and
`@DisallowConcurrentExecution` instead of the default job.

|`fireNow` |`false` |If it is true will fire the trigger when the route
is start when using SimpleTrigger.

|`deleteJob` |`true` |If set to true, then the trigger automatically
delete when route stop. Else if set to false, it will remain in
scheduler. When set to false, it will also mean user may reuse
pre-configured trigger with camel Uri. Just ensure the names match.
Notice you cannot have both deleteJob and pauseJob set to true.

|`pauseJob` |`false` |If set to true, then the trigger automatically
pauses when route stop. Else if set to false, it will remain in
scheduler. When set to false, it will also mean user may reuse
pre-configured trigger with camel Uri. Just ensure the names match.
Notice you cannot have both deleteJob and pauseJob set to true.

|`durableJob` |`false` |*Camel 2.12.4/2.13*: Whether or not the job
should remain stored after it is orphaned (no triggers point to it).

|`recoverableJob` |`false` |*Camel 2.12.4/2.13*: Instructs the scheduler
whether or not the job should be re-executed if a 'recovery' or
'fail-over' situation is +
encountered.

|`usingFixedCamelContextName` |`false` |**Camel 2.15.0:** If it is true,
JobDataMap uses the CamelContext name directly to reference the camel
context, if it is false, JobDataMap uses use the CamelContext management
name which could be changed during the deploy time.

|`customCalendar` |_None_ |**Camel 2.17.0:** Add a custom calendar to
Scheduler and Triggers to avoid specific date range (Holidays for
example). The customCalendar type is: *org.quartz.Calendar*
|=======================================================================

For example, the following routing rule will fire two timer events to
the `mock:results` endpoint:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("quartz2://myGroup/myTimerName?trigger.repeatInterval=2&trigger.repeatCount=1").routeId("myRoute").to("mock:result");
----

When using `stateful=true`, the
http://quartz-scheduler.org/api/2.0.0/org/quartz/JobDataMap.html[JobDataMap]
is re-persisted after every execution of the job, thus preserving state
for the next execution.

[Info]
====
 **Running in OSGi and having multiple bundles with quartz
routes**

If you run in OSGi such as Apache ServiceMix, or Apache Karaf, and have
multiple bundles with Camel routes that start from
link:quartz2.html[Quartz2] endpoints, then make sure if you assign +
an `id` to the <camelContext> that this id is unique, as this is
required by the `QuartzScheduler` in the OSGi container. If you do not
set any `id` on <camelContext> then +
a unique id is auto assigned, and there is no problem.

====

[[Quartz2-Configuringquartz.propertiesfile]]
Configuring quartz.properties file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

By default Quartz will look for a `quartz.properties` file in the
`org/quartz` directory of the classpath. If you are using WAR
deployments this means just drop the quartz.properties in
`WEB-INF/classes/org/quartz`.

However the Camel link:quartz2.html[Quartz2] component also allows you
to configure properties:

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|Parameter |Default |Type |Description
|`properties` |`null` |`Properties` |You can configure a
`java.util.Properties` instance.

|`propertiesFile` |`null` |`String` |File name of the properties to load
from the classpath
|=======================================================================

To do this you can configure this in Spring XML as follows

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<bean id="quartz" class="org.apache.camel.component.quartz2.QuartzComponent">
    <property name="propertiesFile" value="com/mycompany/myquartz.properties"/>
</bean>
----

[[Quartz2-EnablingQuartzschedulerinJMX]]
Enabling Quartz scheduler in JMX
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You need to configure the quartz scheduler properties to enable JMX. +
That is typically setting the option `"org.quartz.scheduler.jmx.export"`
to a `true` value in the configuration file.

From Camel 2.13 onwards Camel will automatic set this option to true,
unless explicit disabled.

[[Quartz2-StartingtheQuartzscheduler]]
Starting the Quartz scheduler
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The link:quartz2.html[Quartz2] component offers an option to let the
Quartz scheduler be started delayed, or not auto started at all.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|Parameter |Default |Type |Description
|`startDelayedSeconds` |`0` |`int` |Seconds to wait before starting the
quartz scheduler.

|`autoStartScheduler` |`true` |`boolean` |Whether or not the scheduler
should be auto started.
|=======================================================================

To do this you can configure this in Spring XML as follows

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<bean id="quartz2" class="org.apache.camel.component.quartz2.QuartzComponent">
    <property name="startDelayedSeconds" value="5"/>
</bean>
----

[[Quartz2-Clustering]]
Clustering
^^^^^^^^^^

If you use Quartz in clustered mode, e.g. the `JobStore` is clustered.
Then the link:quartz2.html[Quartz2] component will *not* pause/remove
triggers when a node is being stopped/shutdown. This allows the trigger
to keep running on the other nodes in the cluster.

*Note*: When running in clustered node no checking is done to ensure
unique job name/group for endpoints.

[[Quartz2-MessageHeaders]]
Message Headers
^^^^^^^^^^^^^^^

Camel adds the getters from the Quartz Execution Context as header
values. The following headers are added: +
`calendar`, `fireTime`, `jobDetail`, `jobInstance`, `jobRuntTime`,
`mergedJobDataMap`, `nextFireTime`, `previousFireTime`, `refireCount`,
`result`, `scheduledFireTime`, `scheduler`, `trigger`, `triggerName`,
`triggerGroup`.

The `fireTime` header contains the `java.util.Date` of when the exchange
was fired.

[[Quartz2-UsingCronTriggers]]
Using Cron Triggers
^^^^^^^^^^^^^^^^^^^

Quartz supports
http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger[Cron-like
expressions] for specifying timers in a handy format. You can use these
expressions in the `cron` URI parameter; though to preserve valid URI
encoding we allow + to be used instead of spaces.

For example, the following will fire a message every five minutes
starting at 12pm (noon) to 6pm on weekdays:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("quartz2://myGroup/myTimerName?cron=0+0/5+12-18+?+*+MON-FRI").to("activemq:Totally.Rocks");
----

which is equivalent to using the cron expression

[source,brush:,java;,gutter:,false;,theme:,Default]
----
0 0/5 12-18 ? * MON-FRI
----

The following table shows the URI character encodings we use to preserve
valid URI syntax:

[width="100%",cols="50%,50%",options="header",]
|=============================
|URI Character |Cron character
|`+` |_Space_
|=============================

[[Quartz2-Specifyingtimezone]]
Specifying time zone
^^^^^^^^^^^^^^^^^^^^

The Quartz Scheduler allows you to configure time zone per trigger. For
example to use a timezone of your country, then you can do as follows:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
quartz2://groupName/timerName?cron=0+0/5+12-18+?+*+MON-FRI&trigger.timeZone=Europe/Stockholm
----

The timeZone value is the values accepted by `java.util.TimeZone`.

[[Quartz2-UsingQuartzScheduledPollConsumerScheduler]]
Using QuartzScheduledPollConsumerScheduler
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The link:quartz2.html[Quartz2] component provides a
link:polling-consumer.html[Polling Consumer] scheduler which allows to
use cron based scheduling for link:polling-consumer.html[Polling
Consumer] such as the link:file2.html[File] and link:ftp2.html[FTP]
consumers.

For example to use a cron based expression to poll for files every 2nd
second, then a Camel route can be define simply as:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
    from("file:inbox?scheduler=quartz2&scheduler.cron=0/2+*+*+*+*+?")
       .to("bean:process");
----

Notice we define the `scheduler=quartz2` to instruct Camel to use the
link:quartz2.html[Quartz2] based scheduler. Then we use `scheduler.xxx`
options to configure the scheduler. The link:quartz2.html[Quartz2]
scheduler requires the cron option to be set.

The following options is supported:

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|Parameter |Default |Type |Description
|`quartzScheduler` |`null` |`org.quartz.Scheduler` |To use a custom
Quartz scheduler. If none configure then the shared scheduler from the
link:quartz2.html[Quartz2] component is used.

|`cron` |`null` |`String` |*Mandatory*: To define the cron expression
for triggering the polls.

|`triggerId` |`null` |`String` |To specify the trigger id. If none
provided then an UUID is generated and used.

|`triggerGroup` |`QuartzScheduledPollConsumerScheduler` |`String` |To
specify the trigger group.

|`timeZone` |`Default` |`TimeZone` |The time zone to use for the CRON
trigger.
|=======================================================================

*Important:* Remember configuring these options from the endpoint
link:uris.html[URIs] must be prefixed with `scheduler.`. +
For example to configure the trigger id and group:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
    from("file:inbox?scheduler=quartz2&scheduler.cron=0/2+*+*+*+*+?&scheduler.triggerId=myId&scheduler.triggerGroup=myGroup")
       .to("bean:process");
----

There is also a CRON scheduler in link:spring.html[Spring], so you can
use the following as well:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
    from("file:inbox?scheduler=spring&scheduler.cron=0/2+*+*+*+*+?")
       .to("bean:process");
----

[[Quartz2-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:quartz.html[Quartz]
* link:timer.html[Timer]
