[[ConfluenceContent]]
[[Quartz-QuartzComponent]]
Quartz Component
~~~~~~~~~~~~~~~~

The *quartz:* component provides a scheduled delivery of messages using
the http://www.quartz-scheduler.org/[Quartz Scheduler 1.x]. +
Each endpoint represents a different timer (in Quartz terms, a Trigger
and JobDetail).

[Tip]
====


If you are using Quartz 2.x then from Camel 2.12 onwards there is a
link:quartz2.html[Quartz2] component you should use

====

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-quartz</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

[[Quartz-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
quartz://timerName?options
quartz://groupName/timerName?options
quartz://groupName/timerName?cron=expression
quartz://timerName?cron=expression
----

The component uses either a `CronTrigger` or a `SimpleTrigger`. If no
cron expression is provided, the component uses a simple trigger. If no
`groupName` is provided, the quartz component uses the `Camel` group
name.

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[Quartz-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Parameter |Default |Description
|`cron` |_None_ |Specifies a `cron` expression (not compatible with the
`trigger.*` or `job.*` options).

|`trigger.repeatCount` |`0` |SimpleTrigger: How many times should the
timer repeat?

|`trigger.repeatInterval` |`0` |SimpleTrigger: The amount of time in
milliseconds between repeated triggers.

|`job.name` |`null` |Sets the job name.

|`job.XXX` |`null` |Sets the job option with the `XXX` setter name.

|`trigger.XXX` |`null` |Sets the trigger option with the `XXX` setter
name.

|`stateful` |`false` |Uses a Quartz `StatefulJob` instead of the default
job.

|`fireNow` |`false` |New to Camel 2.2.0, if it is true will fire the
trigger when the route is start when using SimpleTrigger.

|`deleteJob` |`true` |*Camel 2.12:* If set to true, then the trigger
automatically delete when route stop. Else if set to false, it will
remain in scheduler. When set to false, it will also mean user may reuse
pre-configured trigger with camel Uri. Just ensure the names match.
Notice you cannot have both deleteJob and pauseJob set to true.

|`pauseJob` |`false` |*Camel 2.12:* If set to true, then the trigger
automatically pauses when route stop. Else if set to false, it will
remain in scheduler. When set to false, it will also mean user may reuse
pre-configured trigger with camel Uri. Just ensure the names match.
Notice you cannot have both deleteJob and pauseJob set to true.

|`usingFixedCamelContextName` |`false` |**Camel 2.15.0:** If it is true,
JobDataMap uses the CamelContext name directly to reference the camel
context, if it is false, JobDataMap uses use the CamelContext management
name which could be changed during the deploy time.
|=======================================================================

For example, the following routing rule will fire two timer events to
the `mock:results` endpoint:

When using a
http://quartz-scheduler.org/api/2.0.0/org/quartz/StatefulJob.html[StatefulJob],
the
http://quartz-scheduler.org/api/2.0.0/org/quartz/JobDataMap.html[JobDataMap]
is re-persisted after every execution of the job, thus preserving state
for the next execution.

[Info]
====
 **Running in OSGi and having multiple bundles with quartz
routes**

If you run in OSGi such as Apache ServiceMix, or Apache Karaf, and have
multiple bundles with Camel routes that start from
link:quartz.html[Quartz] endpoints, then make sure if you assign +
an `id` to the <camelContext> that this id is unique, as this is
required by the `QuartzScheduler` in the OSGi container. If you do not
set any `id` on <camelContext> then +
a unique id is auto assigned, and there is no problem.

====

[[Quartz-Configuringquartz.propertiesfile]]
Configuring quartz.properties file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

By default Quartz will look for a `quartz.properties` file in the
`org/quartz` directory of the classpath. If you are using WAR
deployments this means just drop the quartz.properties in
`WEB-INF/classes/org/quartz`.

However the Camel link:quartz.html[Quartz] component also allows you to
configure properties:

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|Parameter |Default |Type |Description
|`properties` |`null` |`Properties` |*Camel 2.4*: You can configure a
`java.util.Properties` instance.

|`propertiesFile` |`null` |`String` |*Camel 2.4*: File name of the
properties to load from the classpath
|=======================================================================

To do this you can configure this in Spring XML as follows

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<bean id="quartz" class="org.apache.camel.component.quartz.QuartzComponent">
    <property name="propertiesFile" value="com/mycompany/myquartz.properties"/>
</bean>
----

[[Quartz-EnablingQuartzschedulerinJMX]]
Enabling Quartz scheduler in JMX
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You need to configure the quartz scheduler properties to enable JMX. +
That is typically setting the option `"org.quartz.scheduler.jmx.export"`
to a `true` value in the configuration file.

From Camel 2.13 onwards Camel will automatic set this option to true,
unless explicit disabled.

[[Quartz-StartingtheQuartzscheduler]]
Starting the Quartz scheduler
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

*Available as of Camel 2.4*

The link:quartz.html[Quartz] component offers an option to let the
Quartz scheduler be started delayed, or not auto started at all.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|Parameter |Default |Type |Description
|`startDelayedSeconds` |`0` |`int` |*Camel 2.4*: Seconds to wait before
starting the quartz scheduler.

|`autoStartScheduler` |`true` |`boolean` |*Camel 2.4:* Whether or not
the scheduler should be auto started.
|=======================================================================

To do this you can configure this in Spring XML as follows

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<bean id="quartz" class="org.apache.camel.component.quartz.QuartzComponent">
    <property name="startDelayedSeconds" value="5"/>
</bean>
----

[[Quartz-Clustering]]
Clustering
^^^^^^^^^^

*Available as of Camel 2.4*

If you use Quartz in clustered mode, e.g. the `JobStore` is clustered.
Then from Camel 2.4 onwards the link:quartz.html[Quartz] component will
*not* pause/remove triggers when a node is being stopped/shutdown. This
allows the trigger to keep running on the other nodes in the cluster.

*Note*: When running in clustered node no checking is done to ensure
unique job name/group for endpoints.

[[Quartz-MessageHeaders]]
Message Headers
^^^^^^^^^^^^^^^

Camel adds the getters from the Quartz Execution Context as header
values. The following headers are added: +
`calendar`, `fireTime`, `jobDetail`, `jobInstance`, `jobRuntTime`,
`mergedJobDataMap`, `nextFireTime`, `previousFireTime`, `refireCount`,
`result`, `scheduledFireTime`, `scheduler`, `trigger`, `triggerName`,
`triggerGroup`.

The `fireTime` header contains the `java.util.Date` of when the exchange
was fired.

[[Quartz-UsingCronTriggers]]
Using Cron Triggers
^^^^^^^^^^^^^^^^^^^

Quartz supports
http://www.quartz-scheduler.org/documentation/quartz-2.1.x/tutorials/crontrigger[Cron-like
expressions] for specifying timers in a handy format. You can use these
expressions in the `cron` URI parameter; though to preserve valid URI
encoding we allow + to be used instead of spaces. Quartz provides a
http://www.quartz-scheduler.org/docs/tutorials/crontrigger.html[little
tutorial] on how to use cron expressions.

For example, the following will fire a message every five minutes
starting at 12pm (noon) to 6pm on weekdays:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("quartz://myGroup/myTimerName?cron=0+0/5+12-18+?+*+MON-FRI").to("activemq:Totally.Rocks");
----

which is equivalent to using the cron expression

[source,brush:,java;,gutter:,false;,theme:,Default]
----
0 0/5 12-18 ? * MON-FRI
----

The following table shows the URI character encodings we use to preserve
valid URI syntax:

[width="100%",cols="50%,50%",options="header",]
|=============================
|URI Character |Cron character
|`+` |_Space_
|=============================

[[Quartz-Specifyingtimezone]]
Specifying time zone
^^^^^^^^^^^^^^^^^^^^

*Available as of Camel 2.8.1* +
The Quartz Scheduler allows you to configure time zone per trigger. For
example to use a timezone of your country, then you can do as follows:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
quartz://groupName/timerName?cron=0+0/5+12-18+?+*+MON-FRI&trigger.timeZone=Europe/Stockholm
----

The timeZone value is the values accepted by `java.util.TimeZone`.

In Camel 2.8.0 or older versions you would have to provide your custom
`String` to `java.util.TimeZone` link:type-converter.html[Type
Converter] to be able configure this from the endpoint uri. +
From Camel 2.8.1 onwards we have included such a
link:type-converter.html[Type Converter] in the camel-core.

[[Quartz-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:quartz2.html[Quartz2]
* link:timer.html[Timer]
