[[ConfluenceContent]]
[[Ref-RefComponent]]
Ref Component
~~~~~~~~~~~~~

The *ref:* component is used for lookup of existing endpoints bound in
the link:registry.html[Registry].

[[Ref-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
ref:someName[?options]
----

Where *someName* is the name of an endpoint in the
link:registry.html[Registry] (usually, but not always, the Spring
registry). If you are using the Spring registry, `someName` would be the
bean ID of an endpoint in the Spring registry.

[[Ref-Runtimelookup]]
Runtime lookup
^^^^^^^^^^^^^^

This component can be used when you need dynamic discovery of endpoints
in the link:registry.html[Registry] where you can compute the URI at
runtime. Then you can look up the endpoint using the following code:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
   // lookup the endpoint
   String myEndpointRef = "bigspenderOrder";
   Endpoint endpoint = context.getEndpoint("ref:" + myEndpointRef);
   
   Producer producer = endpoint.createProducer();
   Exchange exchange = producer.createExchange();
   exchange.getIn().setBody(payloadToSend);
   // send the exchange
   producer.process(exchange);
   ...
----

And you could have a list of endpoints defined in the
link:registry.html[Registry] such as:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  <camelContext id="camel" xmlns="http://activemq.apache.org/camel/schema/spring">
      <endpoint id="normalOrder" uri="activemq:order.slow"/>
      <endpoint id="bigspenderOrder" uri="activemq:order.high"/>
      ...
  </camelContext>
----

[[Ref-Sample]]
Sample
^^^^^^

In the sample below we use the `ref:` in the URI to reference the
endpoint with the spring ID, `endpoint2`:

You could, of course, have used the `ref` attribute instead:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
      <to ref="endpoint2"/>
----

Which is the more common way to write it.

[[Ref-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]
