[[ConfluenceContent]]
[[Rest-RestComponent]]
Rest Component
~~~~~~~~~~~~~~

*Available as of Camel 2.14*

The rest component allows to define REST endpoints using the
link:rest-dsl.html[Rest DSL] and plugin to other Camel components as the
REST transport.

 

[[Rest-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  rest://method:path[:uriTemplate]?[options]
----

[[Rest-URIOptions]]
URI Options
^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|`method` |  a|
HTTP method which should be one of:

* *`get`*
* *`post`*
* *`put`*
* *`patch`*
* *`delete`*
* *`head`*
* *`trace`*
* *`connect`*
* *`options`*

|`path` |  a|
The base path which support REST syntax.

See further below for examples.

|`uriTemplate` |  a|
URI template which support REST syntax.

See further below for examples.

|`consumes` |  a|
Media type such as: *`text/xml`* or *`application/json`* this REST
service accepts.

By default we accept all kinds of types.

|`produces` |  |Media type such as: *`text/xml`* or *`application/json`*
this REST service returns.
|=======================================================================

[[Rest-PathanduriTemplatesyntax]]
Path and `uriTemplate` syntax
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The path and *`uriTemplate`* option is defined using a REST syntax where
you define the REST context path using support for parameters. 

[Tip]
====


If no *`uriTemplate`* is configured then path option works the same way.
It does not matter if you configure only path or if you configure both
options. Though configuring both a path and *`uriTemplate`* is a more
common practice with REST.

====

 

The following is a Camel route using a a path only

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  from("rest:get:hello")
    .transform().constant("Bye World");
----

And the following route uses a parameter which is mapped to a Camel
header with the key *`me`*:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  from("rest:get:hello/{me}")
    .transform().simple("Bye ${header.me}");
----

 +

The following examples have configured a base path as *`hello`* and then
have two REST services configured using *`uriTemplate`*'s.

 

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  from("rest:get:hello:/{me}")
    .transform().simple("Hi ${header.me}");
 
  from("rest:get:hello:/french/{me}")
    .transform().simple("Bonjour ${header.me}");
----

[[Rest-Moreexamples]]
More examples
^^^^^^^^^^^^^

See link:rest-dsl.html[Rest DSL] which offers more examples and how you
can use the Rest DSL to define those in a nicer RESTful way.

There is a *camel-example-servlet-rest-tomcat* example in the Apache
Camel distribution, that demonstrates how to use the
link:rest-dsl.html[Rest DSL] with link:servlet.html[SERVLET] as
transport that can be deployed on Apache Tomcat, or similar web
containers.

[[Rest-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:rest-dsl.html[Rest DSL]
* link:servlet.html[SERVLET]
