[[ConfluenceContent]]
[[RMI-RMIComponent]]
RMI Component
~~~~~~~~~~~~~

The *rmi:* component binds link:exchange.html[Exchange]s to the RMI
protocol (JRMP).

Since this binding is just using RMI, normal RMI rules still apply
regarding what methods can be invoked. This component supports only
Exchanges that carry a method invocation from an interface that extends
the http://java.sun.com/j2se/1.3/docs/api/java/rmi/Remote.html[Remote]
interface. All parameters in the method should be either
http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html[Serializable]
or `Remote` objects.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-rmi</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

[[RMI-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
rmi://rmi-regisitry-host:rmi-registry-port/registry-path[?options]
----

For example:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
rmi://localhost:1099/path/to/service
----

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[RMI-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|`method` |`null` |You can set the name of the method to invoke.

|`remoteInterfaces` |`null` |Its now possible to use this option from
*Camel 2.7:* in the XML DSL. It can be a list of interface names
separated by comma.
|=======================================================================

[[RMI-Using]]
Using
^^^^^

To call out to an existing RMI service registered in an RMI registry,
create a route similar to the following:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("pojo:foo").to("rmi://localhost:1099/foo");
----

To bind an existing camel processor or service in an RMI registry,
define an RMI endpoint as follows:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
RmiEndpoint endpoint= (RmiEndpoint) endpoint("rmi://localhost:1099/bar");
endpoint.setRemoteInterfaces(ISay.class);
from(endpoint).to("pojo:bar");
----

Note that when binding an RMI consumer endpoint, you must specify the
`Remote` interfaces exposed.

In XML DSL you can do as follows from *Camel 2.7* onwards:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
    <camel:route>
        <from uri="rmi://localhost:37541/helloServiceBean?remoteInterfaces=org.apache.camel.example.osgi.HelloService"/>
        <to uri="bean:helloServiceBean"/>
    </camel:route>
----

[[RMI-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]
