[[ConfluenceContent]]
[[RunningExamples-RunningExamples]]
Running Examples
~~~~~~~~~~~~~~~~

This section walks you through running the examples which are shipped
with a link:download.html[binary distribution].

[[RunningExamples-Beforeyoustart]]
Before you start
^^^^^^^^^^^^^^^^

First you need to link:download.html[Download] a binary distribution.

To run the demos with maven, you need to
http://maven.apache.org[download and install Apache Maven].

To test your Maven install, change directory to the examples directory
and type:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
mvn -v
----

You should see something like:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
camel-rider:/tmp/camel/examples$ mvn -v
Maven version: 3.0.3
----

[[RunningExamples-RunningtheexamplesinMaven]]
Running the examples in Maven
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To run the link:walk-through-an-example.html[first example] using Maven,
change directory to the example you want to run then issue the following
command:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
mvn exec:java
----

To run the other Spring-based examples such as the
link:spring-example.html[Spring Example], use the
link:camel-maven-plugin.html[Camel Maven Plugin]. For example:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
cd camel-example-spring
mvn camel:run
----

[[RunningExamples-RunningtheexamplesinyourIDE]]
Running the examples in your IDE
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In each example you can run the main() from your IDE.

To create an IDEA project, run

[source,brush:,java;,gutter:,false;,theme:,Default]
----
mvn idea:idea
----

If you are an Eclipse user, run

[source,brush:,java;,gutter:,false;,theme:,Default]
----
mvn eclipse:eclipse
----

You should now be able to open the project(s) in your IDE and run any
main() method you wish.
