[[ConfluenceContent]]
[[RunningRAT-RunningRAT]]
Running RAT
~~~~~~~~~~~

There is a tool called http://code.google.com/p/arat/[ARAT] along with a
http://mojo.codehaus.org/rat-maven-plugin/[maven RAT plugin] which is
very useful for checking the contents of releases and ensuring we don't
miss licenses, headers, notice files and so forth. Note this tool is
intended purely as a safety net; we also want the committers to manually
review releases and check they look fine.

To run the RAT report try

[source,brush:,java;,gutter:,false;,theme:,Default]
----
mvn clean
mvn rat:check -P rat
----

There should then be a file called *target/camel-parent-$VERSION.rat*
which contains the output of the RAT report.

[[RunningRAT-IfRATbarfs]]
If RAT barfs
^^^^^^^^^^^^

Its typically that some local file has caused RAT to break. It could be
some temporary file generated by the build; maybe a unit test case
generated file or some artifact from creating the site or something.

Try running

[source,brush:,java;,gutter:,false;,theme:,Default]
----
svn stat
----

To find the culprits then try re-running RAT. Hopefully future versions
will make it a bit easier to diagnose why it barfs. Incidentally the
root pom has an excludes element so you can always add some excludes in
there to try hide temporary/generated files etc
