[[ConfluenceContent]]
[[SAPNetWeaver-SAPNetWeaverGatewaycomponent]]
SAP NetWeaver Gateway component
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

*Available as of Camel 2.12*

The *sap-netweaver* integrates with the
http://scn.sap.com/community/developer-center/netweaver-gateway[SAP
NetWeaver Gateway] using HTTP transports.

This camel component supports only producer endpoints.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-sap-netweaver</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

[[SAPNetWeaver-URIformat]]
URI format
^^^^^^^^^^

The URI scheme for a sap netweaver gateway component is as follows

[source,brush:,java;,gutter:,false;,theme:,Default]
----
sap-netweaver:https://host:8080/path?username=foo&password=secret
----

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[SAPNetWeaver-Prerequisites]]
Prerequisites
^^^^^^^^^^^^^

You would need to have an account to the SAP NetWeaver system to be able
to leverage this component. SAP provides a
http://scn.sap.com/docs/DOC-31221#section6[demo setup] where you can
requires for an account.

This component uses the basic authentication scheme for logging into SAP
NetWeaver.

[[SAPNetWeaver-Componentandendpointoptions]]
Component and endpoint options
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|`username` |  |Username for account. This is mandatory.

|`password` |  |Password for account. This is mandatory.

|`json` |`true` |Whether to return data in JSON format. If this option
is false, then XML is returned in link:atom.html[Atom] format.

|`jsonAsMap` |`true` |To transform the JSON from a String to a Map in
the message body.

|`flatternMap` |`true` |If the JSON Map contains only a single entry,
then flattern by storing that single entry value as the message body.
|=======================================================================

[[SAPNetWeaver-MessageHeaders]]
Message Headers
^^^^^^^^^^^^^^^

The following headers can be used by the producer.

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Type |Description
|`CamelNetWeaverCommand` |`String` |*Mandatory*: The command to execute
in http://msdn.microsoft.com/en-us/library/cc956153.aspx[MS ADO.Net Data
Service] format.
|=======================================================================

[[SAPNetWeaver-Examples]]
Examples
^^^^^^^^

This example is using the flight demo example from SAP, which is
available online over the internet
http://scn.sap.com/docs/DOC-31221[here].

In the route below we request the SAP NetWeaver demo server using the
following url

[source,brush:,java;,gutter:,false;,theme:,Default]
----
https://sapes1.sapdevcenter.com/sap/opu/odata/IWBEP/RMTSAMPLEFLIGHT_2/
----

And we want to execute the following command

[source,brush:,java;,gutter:,false;,theme:,Default]
----
FlightCollection(AirLineID='AA',FlightConnectionID='0017',FlightDate=datetime'2012-08-29T00%3A00%3A00')
----

To get flight details for the given flight. The command syntax is in
http://msdn.microsoft.com/en-us/library/cc956153.aspx[MS ADO.Net Data
Service] format.

We have the following Camel route

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:start")
    .toF("sap-netweaver:%s?username=%s&password=%s", url, username, password)
    .to("log:response")
    .to("velocity:flight-info.vm")
----

Where url, username, and password is defined as:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
    private String username = "P1909969254";
    private String password = "TODO";
    private String url = "https://sapes1.sapdevcenter.com/sap/opu/odata/IWBEP/RMTSAMPLEFLIGHT_2/";
    private String command = "FlightCollection(AirLineID='AA',FlightConnectionID='0017',FlightDate=datetime'2012-08-29T00%3A00%3A00')";
----

The password is invalid. You would need to create an account at SAP
first to run the demo.

The velocity template is used for formatting the response to a basic
HTML page

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<html>
  <body>
  Flight information:

  <p/>
  <br/>Airline ID: $body["AirLineID"]
  <br/>Aircraft Type: $body["AirCraftType"]
  <br/>Departure city: $body["FlightDetails"]["DepartureCity"]
  <br/>Departure airport: $body["FlightDetails"]["DepartureAirPort"]
  <br/>Destination city: $body["FlightDetails"]["DestinationCity"]
  <br/>Destination airport: $body["FlightDetails"]["DestinationAirPort"]

  </body>
</html>
----

When running the application you get sampel output:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
Flight information:
Airline ID: AA
Aircraft Type: 747-400
Departure city: new york
Departure airport: JFK
Destination city: SAN FRANCISCO
Destination airport: SFO
----

[[SAPNetWeaver-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:http.html[HTTP]
