[[ConfluenceContent]]
[[Scheduler-SchedulerComponent]]
Scheduler Component
~~~~~~~~~~~~~~~~~~~

*Available as of Camel 2.15*

The *scheduler:* component is used to generate message exchanges when a
scheduler fires. This component is similar to the
 link:timer.html[Timer] component, but it offers more functionality in
terms of scheduling. Also this component uses
JDK `ScheduledExecutorService`. Where as the timer uses a JDK `Timer`.

You can only consume events from this endpoint.

[[Scheduler-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
scheduler:name[?options]
----

Where `name` is the name of the scheduler, which is created and shared
across endpoints. So if you use the same name for all your timer
endpoints, only one scheduler thread pool and thread will be used - but
you can configure the thread pool to allow more concurrent threads.

You can append query options to the URI in the following format,
`?option=value&option=value&...`

*Note:* The IN body of the generated exchange is `null`. So
`exchange.getIn().getBody()` returns `null`.

[[Scheduler-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|`initialDelay` |`1000` |Milliseconds before the first poll starts

|`delay` |`500` |Milliseconds before the next poll

|`timeUnit` |`MILLISECONDS` |time unit
for `initialDelay` and `delay` options.

|`useFixedDelay` |`true` |Controls if fixed delay or fixed rate is used.
See http://java.sun.com/j2se/1.5.0/docs/api/java/util/concurrent/ScheduledExecutorService.html[ScheduledExecutorService] in
JDK for details.

|`pollStrategy` |  |A
pluggable `org.apache.camel.PollingConsumerPollingStrategy` allowing you
to provide your custom implementation to control error handling usually
occurred during
the `poll` operation **before** an http://camel.apache.org/exchange.html[Exchange] have
been created and being routed in Camel. In other words the error
occurred while the polling was gathering information, for instance
access to a file network failed so Camel cannot access it to scan for
files. The default implementation will log the caused exception
at `WARN` level and ignore it.

|`runLoggingLevel` |`TRACE` |The consumer logs a start/complete log line
when it polls. This option allows you to configure the logging level for
that.

|`sendEmptyMessageWhenIdle` |`false` |If the polling consumer did not
poll any files, you can enable this option to send an empty message (no
body) instead.

|`greedy` |`false` |If greedy is enabled, then the ScheduledPollConsumer
will run immediately again, if the previous run polled 1 or more
messages.

|`scheduler` |  |Allow to plugin a
custom `org.apache.camel.spi.ScheduledPollConsumerScheduler` to use as
the scheduler for firing when the polling consumer runs. The default
implementation uses the`ScheduledExecutorService` and there is
a http://camel.apache.org/quartz2.html[Quartz2],
and http://camel.apache.org/spring.html[Spring] based which supports
CRON expressions. **Notice:** If using a custom scheduler then the
options for `initialDelay`, `useFixedDelay`, `timeUnit`,
and`scheduledExecutorService` may not be in use. Use the
text `quartz2` to refer to use
the http://camel.apache.org/quartz2.html[Quartz2] scheduler; and use the
text `spring` to use
the http://camel.apache.org/spring.html[Spring] based; and use the
text `#myScheduler` to refer to a custom scheduler by its id in
the http://camel.apache.org/registry.html[Registry].
See http://camel.apache.org/quartz2.html[Quartz2] page for an example.

|`scheduler.xxx` |  |To configure additional properties when using a
custom `scheduler` or any of
the http://camel.apache.org/quartz2.html[Quartz2], http://camel.apache.org/spring.html[Spring]
based scheduler. For example, to specify a cron value for the Spring
based scheduler, use `scheduler.cron`.

|`backoffMultiplier` |`0` |To let the scheduled polling consumer backoff
if there has been a number of subsequent idles/errors in a row. The
multiplier is then the number of polls that will be skipped before the
next actual attempt is happening again. When this option is in use
then `backoffIdleThreshold` and/or `backoffErrorThreshold` must also be
configured.

|`backoffIdleThreshold` |`0` |The number of subsequent idle polls that
should happen before the `backoffMultipler` should kick-in

|`backoffErrorThreshold` |`0` |The number of subsequent error polls
(failed due some error) that should happen before the
`backoffMultipler` should kick-in.
|=======================================================================

[[Scheduler-Moreinformation]]
More information
^^^^^^^^^^^^^^^^

This component is a scheduler
http://camel.apache.org/polling-consumer.html[Polling Consumer] where
you can find more information about the options above, and examples at
the http://camel.apache.org/polling-consumer.html[Polling
Consumer] page.

[[Scheduler-ExchangeProperties]]
Exchange Properties
^^^^^^^^^^^^^^^^^^^

When the timer is fired, it adds the following information as properties
to the `Exchange`:

[width="100%",cols="34%,33%,33%",options="header",]
|======================================================================
|Name |Type |Description
|`Exchange.TIMER_NAME` |`String` |The value of the `name` option.
|`Exchange.TIMER_FIRED_TIME` |`Date` |The time when the consumer fired.
|======================================================================

 

[[Scheduler-Sample]]
Sample
^^^^^^

To set up a route that generates an event every 60 seconds:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
   from("scheduler://foo?period=60s").to("bean:myBean?method=someMethodName");
----

 

The above route will generate an event and then invoke the
`someMethodName` method on the bean called `myBean` in the
link:registry.html[Registry] such as JNDI or link:spring.html[Spring].

And the route in Spring DSL:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  <route>
    <from uri="scheduler://foo?period=60s"/>
    <to uri="bean:myBean?method=someMethodName"/>
  </route>
----

 

[[Scheduler-Forcingtheschedulertotriggerimmediatelywhencompleted]]
Forcing the scheduler to trigger immediately when completed
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To let the scheduler trigger as soon as the previous task is complete,
you can set the option greedy=true. But beware then the scheduler will
keep firing all the time. So use this with caution.

[[Scheduler-Forcingtheschedulertobeidle]]
Forcing the scheduler to be idle
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

There can be use cases where you want the scheduler to trigger and be
greedy. But sometimes you want "tell the scheduler" that there was no
task to poll, so the scheduler can change into idle mode using the
backoff options. To do this you would need to set a property on the
exchange with the key `Exchange.SCHEDULER_POLLED_MESSAGES` to a boolean
value of false. This will cause the consumer to indicate that there was
no messages polled. 

The consumer will otherwise as by default return 1 message polled to the
scheduler, every time the consumer has completed processing the
exchange.

 

[[Scheduler-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:timer.html[Timer]
* link:quartz.html[Quartz]
