[[ConfluenceContent]]
[[ServletTomcatExample-ServletTomcatExample]]
Servlet Tomcat Example
~~~~~~~~~~~~~~~~~~~~~~

*Available as of Camel 2.7*

This example is located in the `examples/camel-example-servlet-tomcat`
directory of the Camel distribution. +
There is a `README.txt` file with instructions how to run it.

If you use maven then you can easily package the example from the
command line:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
mvn package
----

[[ServletTomcatExample-About]]
About
^^^^^

This example demonstrates how you can use link:servlet.html[Servlet] to
expose a http service in a Camel route.

[[ServletTomcatExample-Implementation]]
Implementation
^^^^^^^^^^^^^^

In the `web.xml` file in the `src/main/webapp/WEB-INF` folder the
CamelServlet is defined. This is mandatory to do when using the
link:servlet.html[Servlet] component.

*web.xml*

The route is a simple link:content-based-router.html[Content Based
Router] defined in the DSL XML as shown:

*camel-config.xml*

[[ServletTomcatExample-Runningtheexample]]
Running the example
^^^^^^^^^^^^^^^^^^^

This example runs in Apache Tomcat, so you will have to package the .war
file and copy it to the `webapp` folder of Tomcat, which is the hot
deploy folder.

There is a main page at:
`http://localhost:8080/camel-example-servlet-tomcat` which has more
instructions. +
You can then use a web browser and send a request to the
`http://localhost:8080/camel-example-servlet-tomcat/camel/hello` url.

[[ServletTomcatExample-SeeAlso]]
See Also
^^^^^^^^

* link:examples.html[Examples]
* link:servlet.html[Servlet]
* link:http.html[HTTP]
