[[ConfluenceContent]]
[[SpringSecurityExample-SpringSecurityExample]]
Spring Security Example
~~~~~~~~~~~~~~~~~~~~~~~

The link:spring-security.html[camel-spring-security] module provides
authentication and authorization capabilities via
http://static.springsource.org/spring-security/site/index.html[Spring
Security]. This example shows you how to use this functionality to
implement a role based authorization application.

This example consumes messages from a servlet endpoint which is secured
by Spring Security with http basic authentication, there are two
services:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
 "http://localhost:8080/camel/user" is for the authenticated user whose role is ROLE_USER
 "http://localhost:8080/camel/admin" is for the authenticated user whose role is ROLE_ADMIN
----

You will need to compile this example first:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  cd $CAMEL_HOME/examples/camel-example-spring-security
  mvn clean install
----

To run the example, you need to start up the server by typing

[source,brush:,java;,gutter:,false;,theme:,Default]
----
  mvn jetty:run
----

To stop the server hit ctrl + c

Then you can use the script in the client directory to send the request
and check the response, or use browser to access upper service with the
user/password ("jim/jimspassword" with the admin and user role or
"rob/robspassword" with user role).

Here is the camel route configuration:

You can find how to configure the camel-servlet with http basic
authentication by check the files in
https://svn.apache.org/repos/asf/camel/trunk/examples/camel-example-spring-security/src/main/webapp/WEB-INF[WEB-INF]
