[[ConfluenceContent]]
[[SpringXQueryExample-SpringXQueryExample]]
Spring XQuery Example
~~~~~~~~~~~~~~~~~~~~~

The Spring XQuery example uses no Java code; its configured purely using
a link:spring.html[Spring] XML configuration file. It parsers some files
from a directory, transforms them using link:xquery.html[XQuery] then
sends them to a message queue. To make it easy to look at the generated
files, we also have another route which consumes from the JMS queue and
writes them to an output directory.

[[SpringXQueryExample-Runningtheexample]]
Running the example
^^^^^^^^^^^^^^^^^^^

To run the example we use the link:camel-maven-plugin.html[Camel Maven
Plugin].

For example from the source or binary distribution the following should
work

[source,brush:,java;,gutter:,false;,theme:,Default]
----
cd examples/camel-example-spring-xquery
mvn camel:run
----

You should now see the generated files in the *target/outputFiles*
directory which are the transformed messages read from the JMS queue.

[[SpringXQueryExample-Codewalkthrough]]
Code walk through
^^^^^^^^^^^^^^^^^

What this does is boot up the Spring ApplicationContext defined in the
file
http://svn.apache.org/repos/asf/camel/trunk/examples/camel-example-spring-xquery/src/main/resources/META-INF/spring/camelContext.xml[META-INF/spring/camelContext.xml]
on the classpath. This is a regular Spring XML document which uses the
Camel link:xml-configuration.html[Xml Configuration] to configure a
link:camelcontext.html[CamelContext].

Also note at the end of this
http://svn.apache.org/repos/asf/camel/trunk/examples/camel-example-spring-xquery/src/main/resources/META-INF/spring/camelContext.xml[XML
example file] we explicitly configure the link:activemq.html[ActiveMQ]
component with details of how to connect to the broker.

The main part of the Spring XML file is here...
