[[ConfluenceContent]]
[[SQL-SQLLanguage]]
SQL Language
~~~~~~~~~~~~

The SQL support is added by http://josql.sourceforge.net/[JoSQL] and is
primarily used for performing SQL queries on in-memory objects. If you
prefer to perform actual database queries then check out the
link:jpa.html[JPA] component.

[Tip]
====
 **Looking for the SQL component**

Camel has both a link:sql.html[SQL] language and a
link:sql-component.html[SQL Component]. This page is about the SQL
language. Click on link:sql-component.html[SQL Component] if you are
looking for the component instead.

====

To use SQL in your camel routes you need to add the a dependency on
*camel-josql* which implements the SQL language.

If you use maven you could just add the following to your pom.xml,
substituting the version number for the latest & greatest release (see
link:download.html[the download page for the latest versions]).

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-josql</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel core version -->
</dependency>
----

Camel supports http://en.wikipedia.org/wiki/SQL[SQL] to allow an
link:expression.html[Expression] or link:predicate.html[Predicate] to be
used in the link:dsl.html[DSL] or link:xml-configuration.html[Xml
Configuration]. For example you could use SQL to create an
link:predicate.html[Predicate] in a link:message-filter.html[Message
Filter] or as an link:expression.html[Expression] for a
link:recipient-list.html[Recipient List].

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("queue:foo").setBody().sql("select * from MyType").to("queue:bar")
----

And the spring DSL:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
   <from uri="queue:foo"/>
   <setBody>
       <sql>select * from MyType</sql>
   </setBody>
   <to uri="queue:bar"/>
----

[[SQL-Variables]]
Variables
^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Variable |Type |Description
|exchange |Exchange |the Exchange object

|in |Message |the exchange.in message

|out |Message |the exchange.out message

|the property key |Object |the Exchange properties

|the header key |Object |the exchange.in headers

|the variable key |Object |if any additional variables is added using
`setVariables` method
|=======================================================================

[[SQL-Loadingscriptfromexternalresource]]
Loading script from external resource
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

*Available as of Camel 2.11*

You can externalize the script and have Camel load it from a resource
such as `"classpath:"`, `"file:"`, or `"http:"`. +
This is done using the following syntax: `"resource:scheme:location"`,
eg to refer to a file on the classpath you can do:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
.setHeader("myHeader").sql("resource:classpath:mysql.sql")
----
