[[ConfluenceContent]]
[[Stomp-StompComponent]]
Stomp Component
~~~~~~~~~~~~~~~

*Available as of Camel 2.12*

The *stomp:* component is used for communicating with
http://stomp.github.io/[Stomp] compliant message brokers, like
http://activemq.apache.org[Apache ActiveMQ] or
http://activemq.apache.org/apollo/[ActiveMQ Apollo]

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-stomp</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

[[Stomp-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
stomp:queue:destination[?options]
----

Where *destination* is the name of the queue.

[[Stomp-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Property |Default |Description
|`brokerURL` |`tcp://localhost:61613` |The URI of the Stomp broker to
connect to

|`login` |  |The username

|`passcode` |  |The password

|host |  |*Camel 2.15.3/2.16:* The virtual host

|sslContextParameters |null |**Camel 2.17:** Reference to
a `org.apache.camel.util.jsse.SSLContextParameters` in
the http://camel.apache.org/registry.html[Registry].  The brokerURL
should use ssl as protocol.
See https://cwiki.apache.org/confluence/display/CAMEL/Camel+Configuration+Utilities[Using
the JSSE Configuration Utility].
|=======================================================================

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[Stomp-Samples]]
Samples
^^^^^^^

Sending messages:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:foo").to("stomp:queue:test");
----

Consuming messages:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("stomp:queue:test").transform(body().convertToString()).to("mock:result")
----

[[Stomp-Endpoints]]
Endpoints
~~~~~~~~~

Camel supports the link:message-endpoint.html[Message Endpoint] pattern
using the
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Endpoint.html[Endpoint]
interface. Endpoints are usually created by a
link:component.html[Component] and Endpoints are usually referred to in
the link:dsl.html[DSL] via their link:uris.html[URIs].

From an Endpoint you can use the following methods

* http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Endpoint.html#createProducer()[createProducer()]
will create a
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Producer.html[Producer]
for sending message exchanges to the endpoint
* http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Endpoint.html#createConsumer(org.apache.camel.Processor)[createConsumer()]
implements the link:event-driven-consumer.html[Event Driven Consumer]
pattern for consuming message exchanges from the endpoint via a
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Processor.html[Processor]
when creating a
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Consumer.html[Consumer]
* http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/Endpoint.html#createPollingConsumer()[createPollingConsumer()]
implements the link:polling-consumer.html[Polling Consumer] pattern for
consuming message exchanges from the endpoint via a
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/PollingConsumer.html[PollingConsumer]

[[Stomp-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:message-endpoint.html[Message Endpoint] pattern
* link:uris.html[URIs]
* link:writing-components.html[Writing Components]
