[[ConfluenceContent]]
[[Twitter-Twitter]]
Twitter
~~~~~~~

*Available as of Camel 2.10*

The Twitter component enables the most useful features of the Twitter
API by encapsulating http://twitter4j.org/[Twitter4J]. It allows direct,
polling, or event-driven consumption of timelines, users, trends, and
direct messages. Also, it supports producing messages as status updates
or direct messages.

Twitter now requires the use of OAuth for all client application
authentication. In order to use camel-twitter with your account, you'll
need to create a new application within Twitter at
https://dev.twitter.com/apps/new and grant the application access to
your account. Finally, generate your access token and secret.

Maven users will need to add the following dependency to their pom.xml
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-twitter</artifactId>
    <version>${camel-version}</version>
</dependency>
----

[[Twitter-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,text;,gutter:,false;,theme:,Default]
----
twitter://endpoint[?options]
----

[[Twitter-TwitterComponent:]]
TwitterComponent:
^^^^^^^^^^^^^^^^^

The twitter component can be configured with the Twitter account
settings which is mandatory to configure before using. +
You can also configure these options directly in the endpoint.

[width="100%",cols="50%,50%",options="header",]
|==========================================
|Option |Description
|consumerKey |The consumer key
|consumerSecret |The consumer secret
|accessToken |The access token
|accessTokenSecret |The access token secret
|==========================================

[[Twitter-ConsumerEndpoints:]]
Consumer Endpoints:
^^^^^^^^^^^^^^^^^^^

Rather than the endpoints returning a List through one single route
exchange, camel-twitter creates one route exchange per returned object.
As an example, if "timeline/home" results in five statuses, the route
will be executed five times (one for each Status).

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|Endpoint |Context |Body Type |Notice
|directmessage |direct, polling |twitter4j.DirectMessage | 

|search |direct, polling |twitter4j.Status | 

|streaming/filter |event, polling |twitter4j.Status | 

|streaming/sample |event, polling |twitter4j.Status | 

|streaming/user |event, polling a|
twitter4j.Status

....
twitter4j.DirectMessage
....

....
twitter4j.UserList
....

 a|
*Camel 2.16*: To receive tweets from protected users and accounts.

**Camel 2.17**: DirectMessages, Favorites, Lists, Following events are
now supported

|timeline/home |direct, polling |twitter4j.Status | 

|timeline/mentions |direct, polling |twitter4j.Status | 

|[line-through]*timeline/public* |[line-through]*direct, polling*
|[line-through]*twitter4j.Status* |[line-through]*@deprecated. Use
timeline/home or direct/home instead. Removed from *Camel 2.11*
onwards.*

|timeline/retweetsofme |direct, polling |twitter4j.Status | 

|timeline/user |direct, polling |twitter4j.Status | 

|[line-through]*trends/daily* |[line-through]**Camel 2.10.1:* direct,
polling* |[line-through]*twitter4j.Status* |[line-through]*@deprecated.
Removed from Camel 2.11 onwards.*

|[line-through]*trends/weekly* |[line-through]**Camel 2.10.1:* direct,
polling* |[line-through]*twitter4j.Status* |[line-through]*@deprecated.
Removed from Camel 2.11 onwards.*
|=======================================================================

[[Twitter-ProducerEndpoints:]]
Producer Endpoints:
^^^^^^^^^^^^^^^^^^^

[width="100%",cols="50%,50%",options="header",]
|==============================
|Endpoint |Body Type
|directmessage |String
|search |List<twitter4j.Status>
|timeline/user |String
|==============================

[[Twitter-URIOptions]]
URI Options
^^^^^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|type |`direct` |direct, event, or polling

|delay |  |Delay between polls. The value is 60 seconds by default. The
value is in seconds for *Camel 2.16* or older. And in millis seconds
from *Camel 2.17* onwards.

|consumerKey |`null` |Consumer Key. Can also be configured on the
`TwitterComponent` level instead.

|consumerSecret |`null` |Consumer Secret. Can also be configured on the
`TwitterComponent` level instead.

|accessToken |`null` |Access Token. Can also be configured on the
`TwitterComponent` level instead.

|accessTokenSecret |`null` |Access Token Secret. Can also be configured
on the `TwitterComponent` level instead.

|user |`null` |Username, used for user timeline consumption, direct
message production, etc.

|locations |`null` |'lat,lon;lat,lon;...' Bounding boxes, created by
pairs of lat/lons. Can be used for streaming/filter

|keywords |`null` |'foo1,foo2,foo3...' Can be used for search and
streaming/filter. See
https://support.twitter.com/articles/71577-using-advanced-search[Advanced
search] for keywords syntax for searching with for example OR.

|userIds |`null` |'username,username...' Can be used for
streaming/filter

|filterOld |`true` |Filter out old tweets, that has previously been
polled. This state is stored in memory only, and based on last tweet id.
*Since Camel 2.11.0* The search producer supports this option

|sinceId |`1` |*Camel 2.11.0:* The last tweet id which will be used for
pulling the tweets. It is useful when the camel route is restarted after
a long running.

|lang |`null` |*Camel 2.11.0:* The lang string
http://en.wikipedia.org/wiki/ISO_639-1[ISO_639-1] which will be used for
searching

|count |`null` |*Camel 2.11.0:* Limiting number of results per page.

|numberOfPages |`1` |*Camel 2.11.0:* The number of pages result which
you want camel-twitter to consume.

|httpProxyHost |`null` |*Camel 2.12.3:* The http proxy host which can be
used for the camel-twitter.

|httpProxyPort |`null` |*Camel 2.12.3:* The http proxy port which can be
used for the camel-twitter.

|httpProxyUser |`null` |*Camel 2.12.3:* The http proxy user which can be
used for the camel-twitter.

|httpProxyPassword |`null` |*Camel 2.12.3:* The http proxy password
which can be used for the camel-twitter.

|latitude |  |**Camel 2.16:** Used by the non-stream geography search to
search by latitude. You need to configure all the following options:
longitude, latitude, radius, and distanceMetric.

|longitude |  |**Camel 2.16:** Used by the non-stream geography search
to search by longitude. You need to configure all the following options:
longitude, latitude, radius, and distanceMetric.

|radius |  |**Camel 2.16:** Used by the non-stream geography search to
search by radius. You need to configure all the following options:
longitude, latitude, radius, and distanceMetric.

|distanceMetric |km |*Camel 2.16:* Used by the non-stream geography
search, to search by radius using the configured metrics. The unit can
either be mi for miles, or km for kilometers. You need to configure all
the following options: longitude, latitude, radius, and distanceMetric.
|=======================================================================

[[Twitter-Messageheader]]
Message header
^^^^^^^^^^^^^^

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Name |Description
|`CamelTwitterKeywords` |This header is used by the search producer to
change the search key words dynamically.

|`CamelTwitterSearchLanguage` |*Camel 2.11.0:* This header can override
the option of `lang` which set the search language for the search
endpoint dynamically

|`CamelTwitterCount` |*Camel 2.11.0* This header can override the option
of `count` which sets the max twitters that will be returned.

|`CamelTwitterNumberOfPages` |*Camel 2.11.0* This header can converrid
the option of `numberOfPages` which sets how many pages we want to
twitter returns.

|CamelTwitterEvent |**Camel 2.17.0** The type of event received (see
org.apache.camel.component.twitter.consumer.TwitterEventType)

|CamelTwitterUser1..N |**Camel 2.17.0** Identify a party

|CamelTwitterUserRole1..N |**Camel 2.17.0** Identify a party role
|=======================================================================

[[Twitter-Messagebody]]
Message body
^^^^^^^^^^^^

All message bodies utilize objects provided by the Twitter4J API.

[[Twitter-Usecases]]
Use cases
^^^^^^^^^

*API Rate Limits*

Twitter REST APIs encapsulated by http://twitter4j.org/[Twitter4J] are
subjected to https://dev.twitter.com/rest/public/rate-limiting[API Rate
Limiting]. You can find the per method limits in the
https://dev.twitter.com/rest/public/rate-limits[API Rate Limits]
documentation. Note that endpoints/resources not listed in that page are
default to 15 requests per allotted user per window.

[[Twitter-TocreateastatusupdatewithinyourTwitterprofile,sendthisproduceraStringbody.]]
To create a status update within your Twitter profile, send this
producer a String body.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:foo")
  .to("twitter://timeline/user?consumerKey=[s]&consumerSecret=[s]&accessToken=[s]&accessTokenSecret=[s]);
----

[[Twitter-Topoll,every60sec.,allstatusesonyourhometimeline:]]
To poll, every 60 sec., all statuses on your home timeline:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("twitter://timeline/home?type=polling&delay=60&consumerKey=[s]&consumerSecret=[s]&accessToken=[s]&accessTokenSecret=[s]")
  .to("bean:blah");
----

[[Twitter-Tosearchforallstatuseswiththekeyword'camel':]]
To search for all statuses with the keyword 'camel':
++++++++++++++++++++++++++++++++++++++++++++++++++++

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("twitter://search?type=direct&keywords=camel&consumerKey=[s]&consumerSecret=[s]&accessToken=[s]&accessTokenSecret=[s]")
  .to("bean:blah");
----

[[Twitter-Searchingusingaproducerwithstatickeywords]]
Searching using a producer with static keywords
+++++++++++++++++++++++++++++++++++++++++++++++

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:foo")
  .to("twitter://search?keywords=camel&consumerKey=[s]&consumerSecret=[s]&accessToken=[s]&accessTokenSecret=[s]");
----

[[Twitter-Searchingusingaproducerwithdynamickeywordsfromheader]]
Searching using a producer with dynamic keywords from header
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In the bar header we have the keywords we want to search, so we can
assign this value to the `CamelTwitterKeywords` header.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:foo")
  .setHeader("CamelTwitterKeywords", header("bar"))
  .to("twitter://search?consumerKey=[s]&consumerSecret=[s]&accessToken=[s]&accessTokenSecret=[s]");
----

[[Twitter-Example]]
Example
^^^^^^^

See also the link:twitter-websocket-example.html[Twitter Websocket
Example].

[[Twitter-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:twitter-websocket-example.html[Twitter Websocket Example]
