[[ConfluenceContent]]
[[Validate-Validate]]
Validate
~~~~~~~~

*Available as of Camel 2.3*

Validate uses an expression or predicates to validate the contents of a
message. It is useful for ensuring that messages are valid before
attempting to process them.

You can use the validate DSL with all kind of Predicates and
Expressions. Validate evaluates the Predicate/Expression and if it is
false a `PredicateValidationException` is thrown. If it is true message
processing continues.

[[Validate-UsingfromJavaDSL]]
Using from Java DSL
^^^^^^^^^^^^^^^^^^^

The route below will read the file contents and validate them against a
regular expression.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("file://inbox")
  .validate(body(String.class).regex("^\\w{10}\\,\\d{2}\\,\\w{24}$"))
.to("bean:MyServiceBean.processLine");
----

Validate is not limited to the message body. You can also validate the
message header.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("file://inbox")
  .validate(header("bar").isGreaterThan(100))
.to("bean:MyServiceBean.processLine");
----

You can also use validate together with
http://camel.apache.org/simple.html[simple].

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("file://inbox")
  .validate(simple("${in.header.bar} == 100"))
.to("bean:MyServiceBean.processLine");
----

[[Validate-UsingfromSpringDSL]]
Using from Spring DSL
^^^^^^^^^^^^^^^^^^^^^

To use validate in the Spring DSL, the easiest way is to use
http://camel.apache.org/simple.html[simple] expressions.

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<route>
  <from uri="file://inbox"/>
  <validate>
    <simple>${body} regex ^\\w{10}\\,\\d{2}\\,\\w{24}$</simple>
  </validate>
  <beanRef ref="myServiceBean" method="processLine"/>
</route>

<bean id="myServiceBean" class="com.mycompany.MyServiceBean"/>
----

The XML DSL to validate the message header would looks like this:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<route>
  <from uri="file://inbox"/>
  <validate>
    <simple>${in.header.bar} == 100</simple>
  </validate>
  <beanRef ref="myServiceBean" method="processLine"/>
</route>

<bean id="myServiceBean" class="com.mycompany.MyServiceBean"/>
----

[[Validate-UsingThisPattern]]
Using This Pattern
++++++++++++++++++

If you would like to use this EIP Pattern then please read the
link:getting-started.html[Getting Started], you may also find the
link:architecture.html[Architecture] useful particularly the description
of link:endpoint.html[Endpoint] and link:uris.html[URIs]. Then you could
try out some of the link:examples.html[Examples] first before trying
this pattern out.
