[[ConfluenceContent]]
[[Vertx-VertxComponent]]
Vertx Component
~~~~~~~~~~~~~~~

*Available as of Camel 2.12*

The *vertx* component is for working with the http://vertx.io/[Vertx]
http://vertx.io/core_manual_js.html#the-event-bus[EventBus].

The vertx http://vertx.io/core_manual_js.html#the-event-bus[EventBus]
sends and receives JSON events.

[Info]
====


From *Camel 2.16* onwards vertx 3 is in use which requires Java 1.8 at
runtime.

====

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-vertx</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

 

[[Vertx-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
vertx:channelName[?options]
----

[[Vertx-Options]]
Options
^^^^^^^

[width="100%",cols="34%,33%,33%",options="header",]
|=======================================================================
|Name |Default Value |Description
|`pubSub` |`false` |*Camel 2.12.3:* Whether to use publish/subscribe
instead of point to point when sending to a vertx endpoint.
|=======================================================================

....
You can append query options to the URI in the following format, ?option=value&option=value&...
....

[[Vertx-ConnectingtotheexistingVert.xinstance]]
Connecting to the existing Vert.x instance
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

If you would like to connect to the Vert.x instance already existing in
your JVM, you can set the instance on the component level:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
Vertx vertx = ...;
VertxComponent vertxComponent = new VertxComponent();
vertxComponent.setVertx(vertx);
camelContext.addComponent("vertx", vertxComponent);
----

[[Vertx-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]
