[[ConfluenceContent]]
[[VM-VMComponent]]
VM Component
~~~~~~~~~~~~

The *vm:* component provides asynchronous
http://www.eecs.harvard.edu/~mdw/proj/seda/[SEDA] behavior, exchanging
messages on a
http://java.sun.com/j2se/1.5.0/docs/api/java/util/concurrent/BlockingQueue.html[BlockingQueue]
and invoking consumers in a separate thread pool.

This component differs from the link:seda.html[Seda] component in that
VM supports communication across CamelContext instances - so you can use
this mechanism to communicate across web applications (provided that
`camel-core.jar` is on the `system/boot` classpath).

VM is an extension to the link:seda.html[Seda] component.

[[VM-URIformat]]
URI format
^^^^^^^^^^

[source,brush:,java;,gutter:,false;,theme:,Default]
----
vm:queueName[?options]
----

Where *`queueName`* can be any string to uniquely identify the endpoint
within the JVM (or at least within the classloader that loaded
camel-core.jar)

You can append query options to the URI in the following format:
`?option=value&option=value&...`

**Before Camel 2.3 - Same URI must be used for both producer and
consumer**

An exactly identical link:vm.html[VM] endpoint URI *must* be used for
both the producer and the consumer endpoint. Otherwise, Camel will
create a second link:vm.html[VM] endpoint despite that the `queueName`
portion of the URI is identical. For example:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:foo").to("vm:bar?concurrentConsumers=5");

from("vm:bar?concurrentConsumers=5").to("file://output");
----

Notice that we have to use the full URI, including options in both the
producer and consumer.

In Camel 2.4 this has been fixed so that only the queue name must match.
Using the queue name `bar`, we could rewrite the previous exmple as
follows:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:foo").to("vm:bar");

from("vm:bar?concurrentConsumers=5").to("file://output");
----

[[VM-Options]]
Options
^^^^^^^

See the link:seda.html[Seda] component for options and other important
usage details as the same rules apply to the link:vm.html[Vm] component.

[[VM-Samples]]
Samples
^^^^^^^

In the route below we send exchanges across CamelContext instances to a
VM queue named `order.email`:

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("direct:in").bean(MyOrderBean.class).to("vm:order.email");
----

And then we receive exchanges in some other Camel context (such as
deployed in another `.war` application):

[source,brush:,java;,gutter:,false;,theme:,Default]
----
from("vm:order.email").bean(MyOrderEmailSender.class);
----

[[VM-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:seda.html[Seda]
